We can get the data for game franchises from Giantbomb. My api key is f2577eac7f52b72170fc1e8c5f0cebb778f38155

In [55]:
import requests
import json
import pandas as pd
import re
from pathlib import Path
import time
import os

## Scraping franchise IDs

Create the directory to store the raw info

In [56]:
franchises_dir = Path('raw_json\\game_franchises\\franchises')
franchises_dir.mkdir(parents=True, exist_ok=True)

Get all the data from the franchise ids and save as json files

In [ ]:
user_agent = "Joshdharris"
headers = {'User-Agent': user_agent}

for x in range(0, 5550, 100):
    filename = "page{}-{}.json".format(x, x+99)
    if not Path(franchises_dir, filename).is_file():
        url = "https://www.giantbomb.com/api/franchises/?api_key=f2577eac7f52b72170fc1e8c5f0cebb778f38155&format=json&field_list=guid,name,description&offset={}".format(x)
        response = json.loads((requests.get(url, headers=headers)).content)
        with open(Path(franchises_dir, filename), "w") as fileOut:
            json.dump(response, fileOut)

This function will be used multiple times for the raw json files. Here we create an empty dataframe, then open all the json files in a specified directory and add them to the dataframe, before returning the dataframe

In [57]:
def create_dataframe(desired_name, raw_directory, add_path):
    #Create empty dataframe
    desired_name = pd.DataFrame(data=[], columns=None)

    #This line creates a list of all the json files in the directory
    files = list(Path(raw_directory).glob('*.json'))
    
    #Iterate through all json files in directory and add to dataframe
    for file in files:
        with open(file) as filein:
            tempDF = pd.read_json(filein)
            if add_path == True:
                tempDF["path"] = str(file)
            desired_name = pd.concat([desired_name, tempDF])  
    return desired_name

Collate all the downloaded files into a single dataframe

In [58]:
franchise_ids = create_dataframe("franchise_ids", franchises_dir, False)
franchise_ids.sample()

error  limit  offset  number_of_page_results  number_of_total_results  \
70    OK    100     500                     100                     5524   

    status_code                                            results  version  
70            1  {'description': '<p>The National Hockey League...        1

In [59]:
franchise_ids.shape

(5524, 8)

Remove unnecessary rows. Again, create a function as it's used multiple times

In [60]:
def drop_unnecessary_columns(dataframe):
    dataframe = dataframe.drop(["error","limit", "offset", "number_of_page_results", "number_of_total_results", "status_code", "version"], axis = 1)
    return dataframe

In [61]:
franchise_ids = drop_unnecessary_columns(franchise_ids)
franchise_ids.shape

(5524, 1)

Extract information from results

In [62]:
franchise_ids["guid"] = [d.get('guid') for d in franchise_ids.results]
franchise_ids["name"] = [d.get('name') for d in franchise_ids.results]
franchise_ids["description"] = [d.get('description') for d in franchise_ids.results]

Get list of all franchise ids.

In [63]:
franchise_id_list = franchise_ids["guid"].tolist()
print(len(franchise_id_list))

5524


Make sure we have no duplicates of the ids

In [64]:
franchise_ids.guid.duplicated().sum()

0

Check out the resultant dataframe

In [65]:
franchise_ids.sample()

results      guid         name  \
44  {'description': None, 'guid': '3025-977', 'nam...  3025-977  LEGO Racers   

   description  
44        None

Drop the results. Write to csv file

In [67]:
franchise_ids = franchise_ids.drop("results", axis = 1)
franchise_ids.sample()

In [70]:
franchise_ids.to_csv("clean_franchise_ids.csv")

## Scraping game IDs

Create directory for game franchises

In [71]:
games_dir = Path('raw_json\\game_franchises\\games')
games_dir.mkdir(parents=True, exist_ok=True)

Download json files for each franchise. We have a cap of 200 requests an hour, hence we're using a time restriction within the loop to prevent the api from blocking us.

In [ ]:
for id in franchise_id_list:
    filename = "{}.json".format(id)
    if not Path(games_dir, filename).is_file():
        url = "https://www.giantbomb.com/api/franchise/{}/?api_key=f2577eac7f52b72170fc1e8c5f0cebb778f38155&format=json&field_list=games".format(id)
        response = json.loads((requests.get(url, headers=headers)).content)
        with open(Path(games_dir, filename), "w") as fileOut:
            json.dump(response, fileOut)
        time.sleep(18)

Create a games dataframe from all the games in the directory

In [72]:
games_ids = create_dataframe("games_ids", games_dir, True)
games_ids.sample()

error  limit  offset  number_of_page_results  number_of_total_results  \
games    OK      1       0                       1                        1   

       status_code                                            results  \
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   

       version                                           path  
games        1  raw_json\game_franchises\games\3025-4488.json

Edit the path to be franchise ids and rename

In [73]:
games_ids["path"] = games_ids["path"].apply(lambda x : x[31:-5])
games_ids = games_ids.rename(columns = {"path":"franchise_id"})
games_ids

error  limit  offset  number_of_page_results  number_of_total_results  \
games    OK      1       0                       1                        1   
games    OK      1       0                       1                        1   
games    OK      1       0                       1                        1   
games    OK      1       0                       1                        1   
games    OK      1       0                       1                        1   
...     ...    ...     ...                     ...                      ...   
games    OK      1       0                       1                        1   
games    OK      1       0                       1                        1   
games    OK      1       0                       1                        1   
games    OK      1       0                       1                        1   
games    OK      1       0                       1                        1   

       status_code                                            results  \
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
...            ...                                                ...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   

       version franchise_id  
games        1       3025-1  
games        1      3025-10  
games        1     3025-100  
games        1     3025-101  
games        1     3025-102  
...        ...          ...  
games        1      3025-94  
games        1      3025-95  
games        1      3025-97  
games        1      3025-98  
games        1      3025-99  

[5346 rows x 9 columns]

### Retrieving missing values

For some reason we have only 5346 results, but 5524 franchise ids. This is, we discovered, because the api is a little buggy. For some reason, having the field-list restriction on returns an empty result for the missing apis, so the workaround is to download all the information and extract the game information from that. 

In [75]:
# Lists all json files in directory
games_in_dir = os.listdir(games_dir)
# Removes .json extension from names
for i in range(len(games_in_dir)):
    games_in_dir[i] = games_in_dir[i][:-5]
# Creates a new list of all the games in the franchise list, but not in the directory
missing_apis = [x for x in franchise_id_list if x not in games_in_dir]
# Check number of missing files
print(len(missing_apis))

178


We'll put the missing files into a separate directory and make a separate dataframe so we don't mess up anything with the current dataframe

In [76]:
missing_games_dir = Path('raw_json\\game_franchises\\games\\missing')
missing_games_dir.mkdir(parents=True, exist_ok=True)

In [ ]:
for id in missing_apis:
    filename = "{}.json".format(id)
    if not Path(missing_games_dir, filename).is_file():
        url = "https://www.giantbomb.com/api/franchise/{}/?api_key=f2577eac7f52b72170fc1e8c5f0cebb778f38155&format=json".format(id)
        response = json.loads((requests.get(url, headers=headers)).content)
        with open(Path(missing_games_dir, filename), "w") as fileOut:
            json.dump(response, fileOut)

In [77]:
missing_games_ids = create_dataframe("missing_games_ids", missing_games_dir, True)
missing_games_ids

error  limit  offset  number_of_page_results  \
aliases            OK      1       0                       1   
api_detail_url     OK      1       0                       1   
characters         OK      1       0                       1   
concepts           OK      1       0                       1   
date_added         OK      1       0                       1   
...               ...    ...     ...                     ...   
locations          OK      1       0                       1   
name               OK      1       0                       1   
objects            OK      1       0                       1   
people             OK      1       0                       1   
site_detail_url    OK      1       0                       1   

                 number_of_total_results  status_code  \
aliases                                1            1   
api_detail_url                         1            1   
characters                             1            1   
concepts                               1            1   
date_added                             1            1   
...                                  ...          ...   
locations                              1            1   
name                                   1            1   
objects                                1            1   
people                                 1            1   
site_detail_url                        1            1   

                                                           results  version  \
aliases                                                       None        1   
api_detail_url   https://www.giantbomb.com/api/franchise/3025-1...        1   
characters       [{'api_detail_url': 'https://www.giantbomb.com...        1   
concepts         [{'api_detail_url': 'https://www.giantbomb.com...        1   
date_added                                     2008-08-25 13:52:36        1   
...                                                            ...      ...   
locations        [{'api_detail_url': 'https://www.giantbomb.com...        1   
name                                                   Shaman King        1   
objects          [{'api_detail_url': 'https://www.giantbomb.com...        1   
people           [{'api_detail_url': 'https://www.giantbomb.com...        1   
site_detail_url    https://www.giantbomb.com/shaman-king/3025-999/        1   

                                                              path  
aliases          raw_json\game_franchises\games\missing\3025-10...  
api_detail_url   raw_json\game_franchises\games\missing\3025-10...  
characters       raw_json\game_franchises\games\missing\3025-10...  
concepts         raw_json\game_franchises\games\missing\3025-10...  
date_added       raw_json\game_franchises\games\missing\3025-10...  
...                                                            ...  
locations        raw_json\game_franchises\games\missing\3025-99...  
name             raw_json\game_franchises\games\missing\3025-99...  
objects          raw_json\game_franchises\games\missing\3025-99...  
people           raw_json\game_franchises\games\missing\3025-99...  
site_detail_url  raw_json\game_franchises\games\missing\3025-99...  

[3204 rows x 9 columns]

We'll remove any rows that don't contain the game listings, rename the path column and extract the games ids

In [78]:
missing_games_ids = missing_games_ids.drop(missing_games_ids.index.difference(['games']))
missing_games_ids["path"] = missing_games_ids["path"].apply(lambda x : x[39:-5])
missing_games_ids = missing_games_ids.rename(columns = {"path":"franchise_id"})

<ipython-input-78-7780a6cf1ad9>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_games_ids["path"] = missing_games_ids["path"].apply(lambda x : x[39:-5])


In [79]:
missing_games_ids.shape

(178, 9)

In [80]:
missing_games_ids.sample()

error  limit  offset  number_of_page_results  number_of_total_results  \
games    OK      1       0                       1                        1   

       status_code                                            results  \
games            1  [{'api_detail_url': 'https://www.giantbomb.com...   

       version franchise_id  
games        1     3025-921

Finally, we'll combine our two dataframes to reintegrate the missing values into our original dataframe

In [81]:
games_ids = pd.concat([games_ids, missing_games_ids])
games_ids.franchise_id.count()

5524

And we can now see we have all the values we expected.

### Working with the combined dataframe

Remove the unnecessary columns, so we're jsut left with results and franchise ids.

In [82]:
games_ids = drop_unnecessary_columns(games_ids)
games_ids.sample()

results franchise_id
games      []    3025-3734

Explode the results so every game has its own row

In [83]:
games_ids = games_ids.explode("results")
games_ids.count()

results         35117
franchise_id    35139
dtype: int64

We have some empty results so we'll drop those before moving on

In [85]:
games_ids = games_ids.dropna()
games_ids.count()

results         35117
franchise_id    35117
dtype: int64

We extract individual game names and ids. We can also extract the individual game ids so we can do further analysis on other games

In [86]:
games_ids[["game_id", "name", "api_url"]] = games_ids["results"].apply(lambda x: pd.Series([x["id"], x["name"], x["api_detail_url"]]))

In [87]:
games_ids["game_id"].nunique()

29208

There's 29208 unique game ids which implies that around 6000 of our games are in multiple franchises. we can look at the ids of the games in the most franchises

In [88]:
games_ids["game_id"].value_counts().head()

6949     7
33847    6
73766    6
569      6
38379    5
Name: game_id, dtype: int64

In [89]:
games_ids = games_ids.drop("results", axis = 1)
games_ids.sample()

franchise_id  game_id  \
games     3025-468    36303   

                                                    name  \
games  One Piece: Treasure Wars 2 - Welcome to Buggyland   

                                              api_url  
games  https://www.giantbomb.com/api/game/3030-36303/

## Scraping additional game metadata

We need additional metadata for the games so we'll create the relevant folder to hold the raw json, extract all the unique ids, combined with the api address. Then download it all

In [4]:
game_dir = Path('raw_json\\game_franchises\\game')
game_dir.mkdir(parents=True, exist_ok=True)

In [47]:
game_api_dict = dict(zip(games_ids["game_id"].unique(), games_ids["api_url"].unique()))
print(len(game_api_dict))

29208


In [ ]:
for game_id, api_url in game_api_dict.items():
    filename = "{}.json".format(game_id)
    if not Path(game_dir, filename).is_file():
        url = "{}?api_key=f2577eac7f52b72170fc1e8c5f0cebb778f38155&format=json".format(api_url)
        response = json.loads((requests.get(url, headers=headers)).content)
        with open(Path(game_dir, filename), "w") as fileOut:
            json.dump(response, fileOut)
        time.sleep(18)

### Combining the game metadata

We want to also combine the year for each game in the giantbomb database to the relevant game. We create a list for each game and their release year then combine them into a dataframe

In [5]:
metadataframe = create_dataframe("metadataframe", game_dir, True)
metadataframe.sample()

KeyboardInterrupt: 

In [ ]:
metadataframe["path"] = metadataframe["path"].apply(lambda x : x[29:-5])
metadataframe = metadataframe.rename(columns = {"path":"game_id"})

In [14]:
with open ("raw_json/game_franchises/game/1.json") as file:
    temp = pd.read_json(file)
temp["results"]

aliases                                                    Desert Strike Advance
api_detail_url                        https://www.giantbomb.com/api/game/3030-1/
characters                                                                  None
concepts                       [{'api_detail_url': 'https://www.giantbomb.com...
date_added                                                   2008-04-01 01:32:48
date_last_updated                                            2021-08-15 16:32:37
deck                           A top-down isometric helicopter shoot 'em up o...
description                    <h2>Overview</h2><p>Desert Strike: Return to t...
developers                     [{'api_detail_url': 'https://www.giantbomb.com...
expected_release_day                                                        None
expected_release_month                                                      None
expected_release_quarter                                                    None
expected_release_year       

In [15]:
ids = []
release_years = []
aliases = []
developers =[]
genres =[]
platforms =[]
publishers =[]
rating = []


files = list(Path("raw_json/game_franchises/game/").glob('*.json'))
for file in files:
    with open(file) as filein:
        tempDF = pd.read_json(filein)
        ids.append(tempDF["results"].get("id"))
        release_years.append(tempDF["results"].get("expected_release_year"))
        aliases.append(tempDF["results"].get("aliases"))
        developers.append(tempDF["results"].get("developers"))
        genres.append(tempDF["results"].get("genres")) 
        platforms.append(tempDF["results"].get("platforms"))
        publishers.append(tempDF["results"].get("publishers")) 
        rating.append(tempDF["results"].get("original_game_rating")) 
        print(file)

raw_json\game_franchises\game\1.json
raw_json\game_franchises\game\1000.json
raw_json\game_franchises\game\10007.json
raw_json\game_franchises\game\10009.json
raw_json\game_franchises\game\1001.json
raw_json\game_franchises\game\10012.json
raw_json\game_franchises\game\10013.json
raw_json\game_franchises\game\10014.json
raw_json\game_franchises\game\10015.json
raw_json\game_franchises\game\1002.json
raw_json\game_franchises\game\10020.json
raw_json\game_franchises\game\10021.json
raw_json\game_franchises\game\10022.json
raw_json\game_franchises\game\10024.json
raw_json\game_franchises\game\1003.json
raw_json\game_franchises\game\10030.json
raw_json\game_franchises\game\10031.json
raw_json\game_franchises\game\10032.json
raw_json\game_franchises\game\10034.json
raw_json\game_franchises\game\10036.json
raw_json\game_franchises\game\10040.json
raw_json\game_franchises\game\10041.json
raw_json\game_franchises\game\10043.json
raw_json\game_franchises\game\10045.json
raw_json\game_franchises

raw_json\game_franchises\game\10406.json
raw_json\game_franchises\game\10408.json
raw_json\game_franchises\game\1041.json
raw_json\game_franchises\game\10410.json
raw_json\game_franchises\game\10416.json
raw_json\game_franchises\game\10419.json
raw_json\game_franchises\game\1042.json
raw_json\game_franchises\game\10425.json
raw_json\game_franchises\game\10426.json
raw_json\game_franchises\game\10429.json
raw_json\game_franchises\game\10431.json
raw_json\game_franchises\game\10434.json
raw_json\game_franchises\game\10438.json
raw_json\game_franchises\game\1044.json
raw_json\game_franchises\game\10442.json
raw_json\game_franchises\game\10447.json
raw_json\game_franchises\game\10448.json
raw_json\game_franchises\game\1045.json
raw_json\game_franchises\game\10450.json
raw_json\game_franchises\game\10459.json
raw_json\game_franchises\game\10460.json
raw_json\game_franchises\game\10461.json
raw_json\game_franchises\game\10465.json
raw_json\game_franchises\game\10466.json
raw_json\game_franch

raw_json\game_franchises\game\10834.json
raw_json\game_franchises\game\10837.json
raw_json\game_franchises\game\10839.json
raw_json\game_franchises\game\1084.json
raw_json\game_franchises\game\10842.json
raw_json\game_franchises\game\10845.json
raw_json\game_franchises\game\10846.json
raw_json\game_franchises\game\10847.json
raw_json\game_franchises\game\10850.json
raw_json\game_franchises\game\10857.json
raw_json\game_franchises\game\10858.json
raw_json\game_franchises\game\10861.json
raw_json\game_franchises\game\10863.json
raw_json\game_franchises\game\10865.json
raw_json\game_franchises\game\10866.json
raw_json\game_franchises\game\10867.json
raw_json\game_franchises\game\10868.json
raw_json\game_franchises\game\1087.json
raw_json\game_franchises\game\10871.json
raw_json\game_franchises\game\10873.json
raw_json\game_franchises\game\10874.json
raw_json\game_franchises\game\10876.json
raw_json\game_franchises\game\10877.json
raw_json\game_franchises\game\10878.json
raw_json\game_fran

raw_json\game_franchises\game\11289.json
raw_json\game_franchises\game\1129.json
raw_json\game_franchises\game\11290.json
raw_json\game_franchises\game\11292.json
raw_json\game_franchises\game\11293.json
raw_json\game_franchises\game\11297.json
raw_json\game_franchises\game\113.json
raw_json\game_franchises\game\11300.json
raw_json\game_franchises\game\11302.json
raw_json\game_franchises\game\11305.json
raw_json\game_franchises\game\11310.json
raw_json\game_franchises\game\11311.json
raw_json\game_franchises\game\11312.json
raw_json\game_franchises\game\11314.json
raw_json\game_franchises\game\11315.json
raw_json\game_franchises\game\11321.json
raw_json\game_franchises\game\11322.json
raw_json\game_franchises\game\11324.json
raw_json\game_franchises\game\11325.json
raw_json\game_franchises\game\11328.json
raw_json\game_franchises\game\11329.json
raw_json\game_franchises\game\11331.json
raw_json\game_franchises\game\11332.json
raw_json\game_franchises\game\11339.json
raw_json\game_franc

raw_json\game_franchises\game\11793.json
raw_json\game_franchises\game\11794.json
raw_json\game_franchises\game\11796.json
raw_json\game_franchises\game\11799.json
raw_json\game_franchises\game\1180.json
raw_json\game_franchises\game\11800.json
raw_json\game_franchises\game\11802.json
raw_json\game_franchises\game\1181.json
raw_json\game_franchises\game\11811.json
raw_json\game_franchises\game\11812.json
raw_json\game_franchises\game\11813.json
raw_json\game_franchises\game\11816.json
raw_json\game_franchises\game\11817.json
raw_json\game_franchises\game\11820.json
raw_json\game_franchises\game\11822.json
raw_json\game_franchises\game\11823.json
raw_json\game_franchises\game\11826.json
raw_json\game_franchises\game\11829.json
raw_json\game_franchises\game\11830.json
raw_json\game_franchises\game\11831.json
raw_json\game_franchises\game\11832.json
raw_json\game_franchises\game\11837.json
raw_json\game_franchises\game\11841.json
raw_json\game_franchises\game\11843.json
raw_json\game_fran

raw_json\game_franchises\game\12285.json
raw_json\game_franchises\game\12286.json
raw_json\game_franchises\game\12287.json
raw_json\game_franchises\game\12288.json
raw_json\game_franchises\game\12291.json
raw_json\game_franchises\game\12294.json
raw_json\game_franchises\game\12295.json
raw_json\game_franchises\game\12297.json
raw_json\game_franchises\game\12298.json
raw_json\game_franchises\game\12300.json
raw_json\game_franchises\game\12301.json
raw_json\game_franchises\game\12303.json
raw_json\game_franchises\game\12305.json
raw_json\game_franchises\game\12306.json
raw_json\game_franchises\game\12309.json
raw_json\game_franchises\game\12311.json
raw_json\game_franchises\game\12312.json
raw_json\game_franchises\game\12313.json
raw_json\game_franchises\game\12315.json
raw_json\game_franchises\game\12317.json
raw_json\game_franchises\game\12318.json
raw_json\game_franchises\game\12321.json
raw_json\game_franchises\game\12328.json
raw_json\game_franchises\game\12329.json
raw_json\game_fr

raw_json\game_franchises\game\12760.json
raw_json\game_franchises\game\12764.json
raw_json\game_franchises\game\12769.json
raw_json\game_franchises\game\12771.json
raw_json\game_franchises\game\12773.json
raw_json\game_franchises\game\12778.json
raw_json\game_franchises\game\12782.json
raw_json\game_franchises\game\12784.json
raw_json\game_franchises\game\12785.json
raw_json\game_franchises\game\12789.json
raw_json\game_franchises\game\12791.json
raw_json\game_franchises\game\12793.json
raw_json\game_franchises\game\12794.json
raw_json\game_franchises\game\12798.json
raw_json\game_franchises\game\1280.json
raw_json\game_franchises\game\12801.json
raw_json\game_franchises\game\12804.json
raw_json\game_franchises\game\12805.json
raw_json\game_franchises\game\12806.json
raw_json\game_franchises\game\12809.json
raw_json\game_franchises\game\12810.json
raw_json\game_franchises\game\12811.json
raw_json\game_franchises\game\12812.json
raw_json\game_franchises\game\12813.json
raw_json\game_fra

raw_json\game_franchises\game\13185.json
raw_json\game_franchises\game\13188.json
raw_json\game_franchises\game\13189.json
raw_json\game_franchises\game\13196.json
raw_json\game_franchises\game\13197.json
raw_json\game_franchises\game\1320.json
raw_json\game_franchises\game\13200.json
raw_json\game_franchises\game\13201.json
raw_json\game_franchises\game\13207.json
raw_json\game_franchises\game\13209.json
raw_json\game_franchises\game\1321.json
raw_json\game_franchises\game\13210.json
raw_json\game_franchises\game\13213.json
raw_json\game_franchises\game\13214.json
raw_json\game_franchises\game\13216.json
raw_json\game_franchises\game\13217.json
raw_json\game_franchises\game\13218.json
raw_json\game_franchises\game\1322.json
raw_json\game_franchises\game\13220.json
raw_json\game_franchises\game\13223.json
raw_json\game_franchises\game\13224.json
raw_json\game_franchises\game\13226.json
raw_json\game_franchises\game\13227.json
raw_json\game_franchises\game\13228.json
raw_json\game_franc

raw_json\game_franchises\game\13662.json
raw_json\game_franchises\game\13664.json
raw_json\game_franchises\game\13665.json
raw_json\game_franchises\game\13666.json
raw_json\game_franchises\game\13667.json
raw_json\game_franchises\game\1367.json
raw_json\game_franchises\game\13671.json
raw_json\game_franchises\game\13672.json
raw_json\game_franchises\game\13674.json
raw_json\game_franchises\game\13676.json
raw_json\game_franchises\game\13678.json
raw_json\game_franchises\game\13679.json
raw_json\game_franchises\game\1368.json
raw_json\game_franchises\game\13681.json
raw_json\game_franchises\game\13682.json
raw_json\game_franchises\game\13683.json
raw_json\game_franchises\game\13685.json
raw_json\game_franchises\game\13688.json
raw_json\game_franchises\game\13694.json
raw_json\game_franchises\game\13696.json
raw_json\game_franchises\game\13697.json
raw_json\game_franchises\game\13698.json
raw_json\game_franchises\game\1370.json
raw_json\game_franchises\game\13700.json
raw_json\game_franc

raw_json\game_franchises\game\14106.json
raw_json\game_franchises\game\14111.json
raw_json\game_franchises\game\14114.json
raw_json\game_franchises\game\14115.json
raw_json\game_franchises\game\14116.json
raw_json\game_franchises\game\14117.json
raw_json\game_franchises\game\14123.json
raw_json\game_franchises\game\14124.json
raw_json\game_franchises\game\14125.json
raw_json\game_franchises\game\14130.json
raw_json\game_franchises\game\14131.json
raw_json\game_franchises\game\14134.json
raw_json\game_franchises\game\14136.json
raw_json\game_franchises\game\14137.json
raw_json\game_franchises\game\14139.json
raw_json\game_franchises\game\14145.json
raw_json\game_franchises\game\14146.json
raw_json\game_franchises\game\14147.json
raw_json\game_franchises\game\1415.json
raw_json\game_franchises\game\14150.json
raw_json\game_franchises\game\14151.json
raw_json\game_franchises\game\14157.json
raw_json\game_franchises\game\14159.json
raw_json\game_franchises\game\1416.json
raw_json\game_fran

raw_json\game_franchises\game\14555.json
raw_json\game_franchises\game\14556.json
raw_json\game_franchises\game\14558.json
raw_json\game_franchises\game\1456.json
raw_json\game_franchises\game\14565.json
raw_json\game_franchises\game\14566.json
raw_json\game_franchises\game\14567.json
raw_json\game_franchises\game\14570.json
raw_json\game_franchises\game\14571.json
raw_json\game_franchises\game\14575.json
raw_json\game_franchises\game\14581.json
raw_json\game_franchises\game\14586.json
raw_json\game_franchises\game\14587.json
raw_json\game_franchises\game\1459.json
raw_json\game_franchises\game\14590.json
raw_json\game_franchises\game\14593.json
raw_json\game_franchises\game\14596.json
raw_json\game_franchises\game\14597.json
raw_json\game_franchises\game\146.json
raw_json\game_franchises\game\14601.json
raw_json\game_franchises\game\14604.json
raw_json\game_franchises\game\14605.json
raw_json\game_franchises\game\14606.json
raw_json\game_franchises\game\14608.json
raw_json\game_franch

raw_json\game_franchises\game\1503.json
raw_json\game_franchises\game\15035.json
raw_json\game_franchises\game\15039.json
raw_json\game_franchises\game\1504.json
raw_json\game_franchises\game\15042.json
raw_json\game_franchises\game\15044.json
raw_json\game_franchises\game\15048.json
raw_json\game_franchises\game\1505.json
raw_json\game_franchises\game\15050.json
raw_json\game_franchises\game\15051.json
raw_json\game_franchises\game\15055.json
raw_json\game_franchises\game\15057.json
raw_json\game_franchises\game\15065.json
raw_json\game_franchises\game\15069.json
raw_json\game_franchises\game\15072.json
raw_json\game_franchises\game\15074.json
raw_json\game_franchises\game\15077.json
raw_json\game_franchises\game\15079.json
raw_json\game_franchises\game\15084.json
raw_json\game_franchises\game\15086.json
raw_json\game_franchises\game\15088.json
raw_json\game_franchises\game\15089.json
raw_json\game_franchises\game\1509.json
raw_json\game_franchises\game\15091.json
raw_json\game_franch

raw_json\game_franchises\game\15497.json
raw_json\game_franchises\game\15501.json
raw_json\game_franchises\game\15502.json
raw_json\game_franchises\game\15504.json
raw_json\game_franchises\game\15508.json
raw_json\game_franchises\game\15509.json
raw_json\game_franchises\game\15510.json
raw_json\game_franchises\game\15511.json
raw_json\game_franchises\game\15512.json
raw_json\game_franchises\game\15514.json
raw_json\game_franchises\game\15516.json
raw_json\game_franchises\game\15517.json
raw_json\game_franchises\game\1552.json
raw_json\game_franchises\game\15522.json
raw_json\game_franchises\game\15523.json
raw_json\game_franchises\game\15525.json
raw_json\game_franchises\game\15526.json
raw_json\game_franchises\game\15529.json
raw_json\game_franchises\game\15533.json
raw_json\game_franchises\game\15534.json
raw_json\game_franchises\game\15536.json
raw_json\game_franchises\game\15537.json
raw_json\game_franchises\game\15544.json
raw_json\game_franchises\game\15549.json
raw_json\game_fra

raw_json\game_franchises\game\1598.json
raw_json\game_franchises\game\15980.json
raw_json\game_franchises\game\15981.json
raw_json\game_franchises\game\15982.json
raw_json\game_franchises\game\15983.json
raw_json\game_franchises\game\15986.json
raw_json\game_franchises\game\15987.json
raw_json\game_franchises\game\15990.json
raw_json\game_franchises\game\15991.json
raw_json\game_franchises\game\15993.json
raw_json\game_franchises\game\15994.json
raw_json\game_franchises\game\15999.json
raw_json\game_franchises\game\1600.json
raw_json\game_franchises\game\16001.json
raw_json\game_franchises\game\16002.json
raw_json\game_franchises\game\16004.json
raw_json\game_franchises\game\16005.json
raw_json\game_franchises\game\16006.json
raw_json\game_franchises\game\16008.json
raw_json\game_franchises\game\16009.json
raw_json\game_franchises\game\1601.json
raw_json\game_franchises\game\16012.json
raw_json\game_franchises\game\16013.json
raw_json\game_franchises\game\16014.json
raw_json\game_franc

raw_json\game_franchises\game\16414.json
raw_json\game_franchises\game\1642.json
raw_json\game_franchises\game\16420.json
raw_json\game_franchises\game\16423.json
raw_json\game_franchises\game\16426.json
raw_json\game_franchises\game\16428.json
raw_json\game_franchises\game\16429.json
raw_json\game_franchises\game\16430.json
raw_json\game_franchises\game\16432.json
raw_json\game_franchises\game\16435.json
raw_json\game_franchises\game\16436.json
raw_json\game_franchises\game\16437.json
raw_json\game_franchises\game\16438.json
raw_json\game_franchises\game\1644.json
raw_json\game_franchises\game\16440.json
raw_json\game_franchises\game\16441.json
raw_json\game_franchises\game\16444.json
raw_json\game_franchises\game\16446.json
raw_json\game_franchises\game\16447.json
raw_json\game_franchises\game\16449.json
raw_json\game_franchises\game\1645.json
raw_json\game_franchises\game\16450.json
raw_json\game_franchises\game\16452.json
raw_json\game_franchises\game\16453.json
raw_json\game_franc

raw_json\game_franchises\game\16909.json
raw_json\game_franchises\game\1691.json
raw_json\game_franchises\game\16913.json
raw_json\game_franchises\game\16916.json
raw_json\game_franchises\game\16921.json
raw_json\game_franchises\game\16922.json
raw_json\game_franchises\game\16926.json
raw_json\game_franchises\game\16927.json
raw_json\game_franchises\game\16928.json
raw_json\game_franchises\game\16932.json
raw_json\game_franchises\game\16933.json
raw_json\game_franchises\game\16937.json
raw_json\game_franchises\game\16938.json
raw_json\game_franchises\game\16939.json
raw_json\game_franchises\game\16941.json
raw_json\game_franchises\game\16942.json
raw_json\game_franchises\game\16944.json
raw_json\game_franchises\game\16945.json
raw_json\game_franchises\game\16946.json
raw_json\game_franchises\game\16948.json
raw_json\game_franchises\game\16949.json
raw_json\game_franchises\game\1695.json
raw_json\game_franchises\game\16951.json
raw_json\game_franchises\game\16954.json
raw_json\game_fran

raw_json\game_franchises\game\17359.json
raw_json\game_franchises\game\17362.json
raw_json\game_franchises\game\17364.json
raw_json\game_franchises\game\17366.json
raw_json\game_franchises\game\17367.json
raw_json\game_franchises\game\1737.json
raw_json\game_franchises\game\17370.json
raw_json\game_franchises\game\17372.json
raw_json\game_franchises\game\17375.json
raw_json\game_franchises\game\17378.json
raw_json\game_franchises\game\17381.json
raw_json\game_franchises\game\17382.json
raw_json\game_franchises\game\17383.json
raw_json\game_franchises\game\17388.json
raw_json\game_franchises\game\17394.json
raw_json\game_franchises\game\17396.json
raw_json\game_franchises\game\17397.json
raw_json\game_franchises\game\17403.json
raw_json\game_franchises\game\17408.json
raw_json\game_franchises\game\17413.json
raw_json\game_franchises\game\17416.json
raw_json\game_franchises\game\17417.json
raw_json\game_franchises\game\17423.json
raw_json\game_franchises\game\17424.json
raw_json\game_fra

raw_json\game_franchises\game\17825.json
raw_json\game_franchises\game\17828.json
raw_json\game_franchises\game\17829.json
raw_json\game_franchises\game\1783.json
raw_json\game_franchises\game\17831.json
raw_json\game_franchises\game\17833.json
raw_json\game_franchises\game\17835.json
raw_json\game_franchises\game\17836.json
raw_json\game_franchises\game\17843.json
raw_json\game_franchises\game\17844.json
raw_json\game_franchises\game\17850.json
raw_json\game_franchises\game\17852.json
raw_json\game_franchises\game\17853.json
raw_json\game_franchises\game\17854.json
raw_json\game_franchises\game\17855.json
raw_json\game_franchises\game\17856.json
raw_json\game_franchises\game\1786.json
raw_json\game_franchises\game\17861.json
raw_json\game_franchises\game\17865.json
raw_json\game_franchises\game\17867.json
raw_json\game_franchises\game\1787.json
raw_json\game_franchises\game\17871.json
raw_json\game_franchises\game\17872.json
raw_json\game_franchises\game\17874.json
raw_json\game_franc

raw_json\game_franchises\game\18305.json
raw_json\game_franchises\game\18309.json
raw_json\game_franchises\game\1831.json
raw_json\game_franchises\game\18314.json
raw_json\game_franchises\game\18315.json
raw_json\game_franchises\game\18317.json
raw_json\game_franchises\game\18320.json
raw_json\game_franchises\game\18324.json
raw_json\game_franchises\game\18326.json
raw_json\game_franchises\game\18327.json
raw_json\game_franchises\game\18328.json
raw_json\game_franchises\game\18331.json
raw_json\game_franchises\game\18333.json
raw_json\game_franchises\game\18336.json
raw_json\game_franchises\game\18338.json
raw_json\game_franchises\game\18339.json
raw_json\game_franchises\game\18341.json
raw_json\game_franchises\game\18345.json
raw_json\game_franchises\game\18346.json
raw_json\game_franchises\game\18347.json
raw_json\game_franchises\game\18348.json
raw_json\game_franchises\game\18350.json
raw_json\game_franchises\game\18355.json
raw_json\game_franchises\game\18357.json
raw_json\game_fra

raw_json\game_franchises\game\18749.json
raw_json\game_franchises\game\18750.json
raw_json\game_franchises\game\18753.json
raw_json\game_franchises\game\18757.json
raw_json\game_franchises\game\18759.json
raw_json\game_franchises\game\18761.json
raw_json\game_franchises\game\18762.json
raw_json\game_franchises\game\18763.json
raw_json\game_franchises\game\18766.json
raw_json\game_franchises\game\18769.json
raw_json\game_franchises\game\18770.json
raw_json\game_franchises\game\18774.json
raw_json\game_franchises\game\18775.json
raw_json\game_franchises\game\18779.json
raw_json\game_franchises\game\1878.json
raw_json\game_franchises\game\18780.json
raw_json\game_franchises\game\18782.json
raw_json\game_franchises\game\18783.json
raw_json\game_franchises\game\18786.json
raw_json\game_franchises\game\18789.json
raw_json\game_franchises\game\18795.json
raw_json\game_franchises\game\18799.json
raw_json\game_franchises\game\1880.json
raw_json\game_franchises\game\18801.json
raw_json\game_fran

raw_json\game_franchises\game\19165.json
raw_json\game_franchises\game\19166.json
raw_json\game_franchises\game\1917.json
raw_json\game_franchises\game\19170.json
raw_json\game_franchises\game\19172.json
raw_json\game_franchises\game\19176.json
raw_json\game_franchises\game\19177.json
raw_json\game_franchises\game\19179.json
raw_json\game_franchises\game\19180.json
raw_json\game_franchises\game\19181.json
raw_json\game_franchises\game\19182.json
raw_json\game_franchises\game\19183.json
raw_json\game_franchises\game\19187.json
raw_json\game_franchises\game\19188.json
raw_json\game_franchises\game\19189.json
raw_json\game_franchises\game\1919.json
raw_json\game_franchises\game\19191.json
raw_json\game_franchises\game\19194.json
raw_json\game_franchises\game\19195.json
raw_json\game_franchises\game\19197.json
raw_json\game_franchises\game\19199.json
raw_json\game_franchises\game\19200.json
raw_json\game_franchises\game\19203.json
raw_json\game_franchises\game\19204.json
raw_json\game_fran

raw_json\game_franchises\game\19614.json
raw_json\game_franchises\game\19617.json
raw_json\game_franchises\game\19618.json
raw_json\game_franchises\game\1962.json
raw_json\game_franchises\game\19621.json
raw_json\game_franchises\game\19626.json
raw_json\game_franchises\game\19628.json
raw_json\game_franchises\game\19630.json
raw_json\game_franchises\game\19633.json
raw_json\game_franchises\game\19636.json
raw_json\game_franchises\game\19641.json
raw_json\game_franchises\game\19645.json
raw_json\game_franchises\game\19646.json
raw_json\game_franchises\game\19647.json
raw_json\game_franchises\game\19649.json
raw_json\game_franchises\game\19656.json
raw_json\game_franchises\game\19658.json
raw_json\game_franchises\game\19663.json
raw_json\game_franchises\game\19665.json
raw_json\game_franchises\game\19669.json
raw_json\game_franchises\game\19674.json
raw_json\game_franchises\game\19676.json
raw_json\game_franchises\game\19678.json
raw_json\game_franchises\game\19680.json
raw_json\game_fra

raw_json\game_franchises\game\20089.json
raw_json\game_franchises\game\20095.json
raw_json\game_franchises\game\20096.json
raw_json\game_franchises\game\20097.json
raw_json\game_franchises\game\20100.json
raw_json\game_franchises\game\20101.json
raw_json\game_franchises\game\20102.json
raw_json\game_franchises\game\20103.json
raw_json\game_franchises\game\20105.json
raw_json\game_franchises\game\20107.json
raw_json\game_franchises\game\20112.json
raw_json\game_franchises\game\20113.json
raw_json\game_franchises\game\20120.json
raw_json\game_franchises\game\20121.json
raw_json\game_franchises\game\20123.json
raw_json\game_franchises\game\20124.json
raw_json\game_franchises\game\20128.json
raw_json\game_franchises\game\20130.json
raw_json\game_franchises\game\20131.json
raw_json\game_franchises\game\20132.json
raw_json\game_franchises\game\20133.json
raw_json\game_franchises\game\20139.json
raw_json\game_franchises\game\20141.json
raw_json\game_franchises\game\20146.json
raw_json\game_fr

raw_json\game_franchises\game\20545.json
raw_json\game_franchises\game\20546.json
raw_json\game_franchises\game\20547.json
raw_json\game_franchises\game\20548.json
raw_json\game_franchises\game\20549.json
raw_json\game_franchises\game\20550.json
raw_json\game_franchises\game\20551.json
raw_json\game_franchises\game\20552.json
raw_json\game_franchises\game\20553.json
raw_json\game_franchises\game\20555.json
raw_json\game_franchises\game\20558.json
raw_json\game_franchises\game\20559.json
raw_json\game_franchises\game\20560.json
raw_json\game_franchises\game\20561.json
raw_json\game_franchises\game\20562.json
raw_json\game_franchises\game\20564.json
raw_json\game_franchises\game\20567.json
raw_json\game_franchises\game\20568.json
raw_json\game_franchises\game\20569.json
raw_json\game_franchises\game\20572.json
raw_json\game_franchises\game\20575.json
raw_json\game_franchises\game\20576.json
raw_json\game_franchises\game\20578.json
raw_json\game_franchises\game\20579.json
raw_json\game_fr

raw_json\game_franchises\game\20822.json
raw_json\game_franchises\game\20823.json
raw_json\game_franchises\game\20827.json
raw_json\game_franchises\game\20829.json
raw_json\game_franchises\game\2083.json
raw_json\game_franchises\game\20830.json
raw_json\game_franchises\game\20831.json
raw_json\game_franchises\game\20832.json
raw_json\game_franchises\game\20834.json
raw_json\game_franchises\game\20835.json
raw_json\game_franchises\game\20836.json
raw_json\game_franchises\game\20837.json
raw_json\game_franchises\game\2084.json
raw_json\game_franchises\game\20846.json
raw_json\game_franchises\game\20848.json
raw_json\game_franchises\game\20850.json
raw_json\game_franchises\game\20851.json
raw_json\game_franchises\game\20852.json
raw_json\game_franchises\game\20854.json
raw_json\game_franchises\game\20855.json
raw_json\game_franchises\game\20857.json
raw_json\game_franchises\game\20858.json
raw_json\game_franchises\game\20860.json
raw_json\game_franchises\game\20866.json
raw_json\game_fran

raw_json\game_franchises\game\21152.json
raw_json\game_franchises\game\21154.json
raw_json\game_franchises\game\21155.json
raw_json\game_franchises\game\21156.json
raw_json\game_franchises\game\21157.json
raw_json\game_franchises\game\21158.json
raw_json\game_franchises\game\21159.json
raw_json\game_franchises\game\21161.json
raw_json\game_franchises\game\21162.json
raw_json\game_franchises\game\21163.json
raw_json\game_franchises\game\21165.json
raw_json\game_franchises\game\21167.json
raw_json\game_franchises\game\21169.json
raw_json\game_franchises\game\21170.json
raw_json\game_franchises\game\21171.json
raw_json\game_franchises\game\21172.json
raw_json\game_franchises\game\21175.json
raw_json\game_franchises\game\21177.json
raw_json\game_franchises\game\21178.json
raw_json\game_franchises\game\21179.json
raw_json\game_franchises\game\21180.json
raw_json\game_franchises\game\21181.json
raw_json\game_franchises\game\21182.json
raw_json\game_franchises\game\21184.json
raw_json\game_fr

raw_json\game_franchises\game\21468.json
raw_json\game_franchises\game\2147.json
raw_json\game_franchises\game\21470.json
raw_json\game_franchises\game\21475.json
raw_json\game_franchises\game\21476.json
raw_json\game_franchises\game\21479.json
raw_json\game_franchises\game\2148.json
raw_json\game_franchises\game\21480.json
raw_json\game_franchises\game\21481.json
raw_json\game_franchises\game\21482.json
raw_json\game_franchises\game\21483.json
raw_json\game_franchises\game\21486.json
raw_json\game_franchises\game\21489.json
raw_json\game_franchises\game\21493.json
raw_json\game_franchises\game\21494.json
raw_json\game_franchises\game\21495.json
raw_json\game_franchises\game\21497.json
raw_json\game_franchises\game\21498.json
raw_json\game_franchises\game\21499.json
raw_json\game_franchises\game\215.json
raw_json\game_franchises\game\2150.json
raw_json\game_franchises\game\21500.json
raw_json\game_franchises\game\21504.json
raw_json\game_franchises\game\21507.json
raw_json\game_franchi

raw_json\game_franchises\game\21776.json
raw_json\game_franchises\game\21777.json
raw_json\game_franchises\game\21778.json
raw_json\game_franchises\game\2178.json
raw_json\game_franchises\game\21780.json
raw_json\game_franchises\game\21782.json
raw_json\game_franchises\game\21783.json
raw_json\game_franchises\game\21784.json
raw_json\game_franchises\game\21788.json
raw_json\game_franchises\game\21789.json
raw_json\game_franchises\game\2179.json
raw_json\game_franchises\game\21790.json
raw_json\game_franchises\game\21794.json
raw_json\game_franchises\game\21796.json
raw_json\game_franchises\game\21798.json
raw_json\game_franchises\game\21799.json
raw_json\game_franchises\game\2180.json
raw_json\game_franchises\game\21800.json
raw_json\game_franchises\game\21802.json
raw_json\game_franchises\game\21804.json
raw_json\game_franchises\game\21805.json
raw_json\game_franchises\game\21806.json
raw_json\game_franchises\game\21808.json
raw_json\game_franchises\game\21809.json
raw_json\game_franc

raw_json\game_franchises\game\22176.json
raw_json\game_franchises\game\22178.json
raw_json\game_franchises\game\22181.json
raw_json\game_franchises\game\22182.json
raw_json\game_franchises\game\22183.json
raw_json\game_franchises\game\22188.json
raw_json\game_franchises\game\2219.json
raw_json\game_franchises\game\22191.json
raw_json\game_franchises\game\22192.json
raw_json\game_franchises\game\22193.json
raw_json\game_franchises\game\22194.json
raw_json\game_franchises\game\22195.json
raw_json\game_franchises\game\22198.json
raw_json\game_franchises\game\22199.json
raw_json\game_franchises\game\222.json
raw_json\game_franchises\game\2220.json
raw_json\game_franchises\game\22200.json
raw_json\game_franchises\game\22201.json
raw_json\game_franchises\game\22202.json
raw_json\game_franchises\game\22203.json
raw_json\game_franchises\game\22208.json
raw_json\game_franchises\game\22209.json
raw_json\game_franchises\game\22210.json
raw_json\game_franchises\game\22211.json
raw_json\game_franch

raw_json\game_franchises\game\2253.json
raw_json\game_franchises\game\22530.json
raw_json\game_franchises\game\22532.json
raw_json\game_franchises\game\22533.json
raw_json\game_franchises\game\22535.json
raw_json\game_franchises\game\22538.json
raw_json\game_franchises\game\2254.json
raw_json\game_franchises\game\22546.json
raw_json\game_franchises\game\22547.json
raw_json\game_franchises\game\22548.json
raw_json\game_franchises\game\2255.json
raw_json\game_franchises\game\22550.json
raw_json\game_franchises\game\22551.json
raw_json\game_franchises\game\22552.json
raw_json\game_franchises\game\22554.json
raw_json\game_franchises\game\22562.json
raw_json\game_franchises\game\22564.json
raw_json\game_franchises\game\22569.json
raw_json\game_franchises\game\22570.json
raw_json\game_franchises\game\22571.json
raw_json\game_franchises\game\22572.json
raw_json\game_franchises\game\22573.json
raw_json\game_franchises\game\22574.json
raw_json\game_franchises\game\22575.json
raw_json\game_franc

raw_json\game_franchises\game\22874.json
raw_json\game_franchises\game\22879.json
raw_json\game_franchises\game\2288.json
raw_json\game_franchises\game\22880.json
raw_json\game_franchises\game\22881.json
raw_json\game_franchises\game\22882.json
raw_json\game_franchises\game\22884.json
raw_json\game_franchises\game\22885.json
raw_json\game_franchises\game\22888.json
raw_json\game_franchises\game\22889.json
raw_json\game_franchises\game\22890.json
raw_json\game_franchises\game\22891.json
raw_json\game_franchises\game\22892.json
raw_json\game_franchises\game\22894.json
raw_json\game_franchises\game\22895.json
raw_json\game_franchises\game\22897.json
raw_json\game_franchises\game\22899.json
raw_json\game_franchises\game\229.json
raw_json\game_franchises\game\22904.json
raw_json\game_franchises\game\22905.json
raw_json\game_franchises\game\22906.json
raw_json\game_franchises\game\22910.json
raw_json\game_franchises\game\22911.json
raw_json\game_franchises\game\22913.json
raw_json\game_franc

raw_json\game_franchises\game\23224.json
raw_json\game_franchises\game\23225.json
raw_json\game_franchises\game\23228.json
raw_json\game_franchises\game\23229.json
raw_json\game_franchises\game\23232.json
raw_json\game_franchises\game\23233.json
raw_json\game_franchises\game\23234.json
raw_json\game_franchises\game\23236.json
raw_json\game_franchises\game\23237.json
raw_json\game_franchises\game\23239.json
raw_json\game_franchises\game\2324.json
raw_json\game_franchises\game\23244.json
raw_json\game_franchises\game\23245.json
raw_json\game_franchises\game\23249.json
raw_json\game_franchises\game\2325.json
raw_json\game_franchises\game\23251.json
raw_json\game_franchises\game\23254.json
raw_json\game_franchises\game\23255.json
raw_json\game_franchises\game\2326.json
raw_json\game_franchises\game\23265.json
raw_json\game_franchises\game\23267.json
raw_json\game_franchises\game\23268.json
raw_json\game_franchises\game\23269.json
raw_json\game_franchises\game\23274.json
raw_json\game_franc

raw_json\game_franchises\game\23618.json
raw_json\game_franchises\game\23619.json
raw_json\game_franchises\game\23620.json
raw_json\game_franchises\game\23621.json
raw_json\game_franchises\game\23622.json
raw_json\game_franchises\game\23623.json
raw_json\game_franchises\game\2363.json
raw_json\game_franchises\game\23632.json
raw_json\game_franchises\game\23634.json
raw_json\game_franchises\game\23635.json
raw_json\game_franchises\game\23638.json
raw_json\game_franchises\game\2364.json
raw_json\game_franchises\game\23642.json
raw_json\game_franchises\game\23645.json
raw_json\game_franchises\game\23652.json
raw_json\game_franchises\game\23656.json
raw_json\game_franchises\game\23658.json
raw_json\game_franchises\game\23660.json
raw_json\game_franchises\game\23665.json
raw_json\game_franchises\game\23669.json
raw_json\game_franchises\game\2367.json
raw_json\game_franchises\game\23670.json
raw_json\game_franchises\game\23672.json
raw_json\game_franchises\game\23673.json
raw_json\game_franc

raw_json\game_franchises\game\240.json
raw_json\game_franchises\game\2400.json
raw_json\game_franchises\game\24000.json
raw_json\game_franchises\game\24001.json
raw_json\game_franchises\game\24002.json
raw_json\game_franchises\game\24005.json
raw_json\game_franchises\game\24006.json
raw_json\game_franchises\game\24009.json
raw_json\game_franchises\game\24011.json
raw_json\game_franchises\game\24014.json
raw_json\game_franchises\game\24016.json
raw_json\game_franchises\game\24018.json
raw_json\game_franchises\game\24019.json
raw_json\game_franchises\game\24021.json
raw_json\game_franchises\game\24022.json
raw_json\game_franchises\game\24023.json
raw_json\game_franchises\game\24024.json
raw_json\game_franchises\game\24026.json
raw_json\game_franchises\game\24027.json
raw_json\game_franchises\game\24028.json
raw_json\game_franchises\game\24029.json
raw_json\game_franchises\game\2403.json
raw_json\game_franchises\game\24034.json
raw_json\game_franchises\game\24035.json
raw_json\game_franch

raw_json\game_franchises\game\24335.json
raw_json\game_franchises\game\24337.json
raw_json\game_franchises\game\24338.json
raw_json\game_franchises\game\2434.json
raw_json\game_franchises\game\24344.json
raw_json\game_franchises\game\24345.json
raw_json\game_franchises\game\24346.json
raw_json\game_franchises\game\24347.json
raw_json\game_franchises\game\24348.json
raw_json\game_franchises\game\24349.json
raw_json\game_franchises\game\2435.json
raw_json\game_franchises\game\24350.json
raw_json\game_franchises\game\24351.json
raw_json\game_franchises\game\24352.json
raw_json\game_franchises\game\24353.json
raw_json\game_franchises\game\24354.json
raw_json\game_franchises\game\24359.json
raw_json\game_franchises\game\24360.json
raw_json\game_franchises\game\24362.json
raw_json\game_franchises\game\24368.json
raw_json\game_franchises\game\24369.json
raw_json\game_franchises\game\2437.json
raw_json\game_franchises\game\24370.json
raw_json\game_franchises\game\24371.json
raw_json\game_franc

raw_json\game_franchises\game\24759.json
raw_json\game_franchises\game\24760.json
raw_json\game_franchises\game\24761.json
raw_json\game_franchises\game\24765.json
raw_json\game_franchises\game\24766.json
raw_json\game_franchises\game\24767.json
raw_json\game_franchises\game\24768.json
raw_json\game_franchises\game\24769.json
raw_json\game_franchises\game\24770.json
raw_json\game_franchises\game\24771.json
raw_json\game_franchises\game\24772.json
raw_json\game_franchises\game\24773.json
raw_json\game_franchises\game\24774.json
raw_json\game_franchises\game\24775.json
raw_json\game_franchises\game\24777.json
raw_json\game_franchises\game\2478.json
raw_json\game_franchises\game\24780.json
raw_json\game_franchises\game\24783.json
raw_json\game_franchises\game\24784.json
raw_json\game_franchises\game\24785.json
raw_json\game_franchises\game\24789.json
raw_json\game_franchises\game\24792.json
raw_json\game_franchises\game\24793.json
raw_json\game_franchises\game\24796.json
raw_json\game_fra

raw_json\game_franchises\game\2520.json
raw_json\game_franchises\game\25200.json
raw_json\game_franchises\game\25209.json
raw_json\game_franchises\game\2521.json
raw_json\game_franchises\game\25218.json
raw_json\game_franchises\game\2522.json
raw_json\game_franchises\game\25220.json
raw_json\game_franchises\game\25221.json
raw_json\game_franchises\game\25222.json
raw_json\game_franchises\game\25223.json
raw_json\game_franchises\game\25225.json
raw_json\game_franchises\game\25226.json
raw_json\game_franchises\game\25227.json
raw_json\game_franchises\game\25229.json
raw_json\game_franchises\game\25230.json
raw_json\game_franchises\game\25231.json
raw_json\game_franchises\game\25234.json
raw_json\game_franchises\game\25236.json
raw_json\game_franchises\game\25237.json
raw_json\game_franchises\game\25238.json
raw_json\game_franchises\game\25239.json
raw_json\game_franchises\game\2524.json
raw_json\game_franchises\game\25240.json
raw_json\game_franchises\game\25241.json
raw_json\game_franch

raw_json\game_franchises\game\25588.json
raw_json\game_franchises\game\2559.json
raw_json\game_franchises\game\25596.json
raw_json\game_franchises\game\25598.json
raw_json\game_franchises\game\25601.json
raw_json\game_franchises\game\25605.json
raw_json\game_franchises\game\25606.json
raw_json\game_franchises\game\25607.json
raw_json\game_franchises\game\25608.json
raw_json\game_franchises\game\2561.json
raw_json\game_franchises\game\25610.json
raw_json\game_franchises\game\25611.json
raw_json\game_franchises\game\25613.json
raw_json\game_franchises\game\25614.json
raw_json\game_franchises\game\25615.json
raw_json\game_franchises\game\25620.json
raw_json\game_franchises\game\25621.json
raw_json\game_franchises\game\25622.json
raw_json\game_franchises\game\25624.json
raw_json\game_franchises\game\25628.json
raw_json\game_franchises\game\2563.json
raw_json\game_franchises\game\25630.json
raw_json\game_franchises\game\25636.json
raw_json\game_franchises\game\25637.json
raw_json\game_franc

raw_json\game_franchises\game\25985.json
raw_json\game_franchises\game\25987.json
raw_json\game_franchises\game\25988.json
raw_json\game_franchises\game\25990.json
raw_json\game_franchises\game\25992.json
raw_json\game_franchises\game\25994.json
raw_json\game_franchises\game\25997.json
raw_json\game_franchises\game\2600.json
raw_json\game_franchises\game\26000.json
raw_json\game_franchises\game\26002.json
raw_json\game_franchises\game\26003.json
raw_json\game_franchises\game\26004.json
raw_json\game_franchises\game\26005.json
raw_json\game_franchises\game\26006.json
raw_json\game_franchises\game\26007.json
raw_json\game_franchises\game\26008.json
raw_json\game_franchises\game\26009.json
raw_json\game_franchises\game\26010.json
raw_json\game_franchises\game\26013.json
raw_json\game_franchises\game\26014.json
raw_json\game_franchises\game\2602.json
raw_json\game_franchises\game\26020.json
raw_json\game_franchises\game\26021.json
raw_json\game_franchises\game\26023.json
raw_json\game_fran

raw_json\game_franchises\game\26565.json
raw_json\game_franchises\game\26567.json
raw_json\game_franchises\game\26569.json
raw_json\game_franchises\game\26570.json
raw_json\game_franchises\game\26571.json
raw_json\game_franchises\game\26572.json
raw_json\game_franchises\game\26575.json
raw_json\game_franchises\game\26576.json
raw_json\game_franchises\game\26577.json
raw_json\game_franchises\game\26579.json
raw_json\game_franchises\game\26580.json
raw_json\game_franchises\game\26581.json
raw_json\game_franchises\game\26582.json
raw_json\game_franchises\game\26583.json
raw_json\game_franchises\game\26587.json
raw_json\game_franchises\game\26588.json
raw_json\game_franchises\game\26589.json
raw_json\game_franchises\game\2659.json
raw_json\game_franchises\game\26591.json
raw_json\game_franchises\game\26592.json
raw_json\game_franchises\game\26593.json
raw_json\game_franchises\game\26594.json
raw_json\game_franchises\game\26595.json
raw_json\game_franchises\game\26596.json
raw_json\game_fra

raw_json\game_franchises\game\26975.json
raw_json\game_franchises\game\26976.json
raw_json\game_franchises\game\26980.json
raw_json\game_franchises\game\2699.json
raw_json\game_franchises\game\26990.json
raw_json\game_franchises\game\26993.json
raw_json\game_franchises\game\26994.json
raw_json\game_franchises\game\26996.json
raw_json\game_franchises\game\26997.json
raw_json\game_franchises\game\27.json
raw_json\game_franchises\game\270.json
raw_json\game_franchises\game\27001.json
raw_json\game_franchises\game\27002.json
raw_json\game_franchises\game\27004.json
raw_json\game_franchises\game\27006.json
raw_json\game_franchises\game\27011.json
raw_json\game_franchises\game\27014.json
raw_json\game_franchises\game\27019.json
raw_json\game_franchises\game\2702.json
raw_json\game_franchises\game\27022.json
raw_json\game_franchises\game\27023.json
raw_json\game_franchises\game\27025.json
raw_json\game_franchises\game\27027.json
raw_json\game_franchises\game\27028.json
raw_json\game_franchise

raw_json\game_franchises\game\27411.json
raw_json\game_franchises\game\27413.json
raw_json\game_franchises\game\27415.json
raw_json\game_franchises\game\27417.json
raw_json\game_franchises\game\27419.json
raw_json\game_franchises\game\2744.json
raw_json\game_franchises\game\27442.json
raw_json\game_franchises\game\27443.json
raw_json\game_franchises\game\27447.json
raw_json\game_franchises\game\27448.json
raw_json\game_franchises\game\27449.json
raw_json\game_franchises\game\27450.json
raw_json\game_franchises\game\27451.json
raw_json\game_franchises\game\27453.json
raw_json\game_franchises\game\27454.json
raw_json\game_franchises\game\27455.json
raw_json\game_franchises\game\27468.json
raw_json\game_franchises\game\27470.json
raw_json\game_franchises\game\27471.json
raw_json\game_franchises\game\27485.json
raw_json\game_franchises\game\27486.json
raw_json\game_franchises\game\27487.json
raw_json\game_franchises\game\27489.json
raw_json\game_franchises\game\27493.json
raw_json\game_fra

raw_json\game_franchises\game\2788.json
raw_json\game_franchises\game\27880.json
raw_json\game_franchises\game\27881.json
raw_json\game_franchises\game\27882.json
raw_json\game_franchises\game\27884.json
raw_json\game_franchises\game\27885.json
raw_json\game_franchises\game\27889.json
raw_json\game_franchises\game\2789.json
raw_json\game_franchises\game\27892.json
raw_json\game_franchises\game\27894.json
raw_json\game_franchises\game\27895.json
raw_json\game_franchises\game\27896.json
raw_json\game_franchises\game\27898.json
raw_json\game_franchises\game\279.json
raw_json\game_franchises\game\27900.json
raw_json\game_franchises\game\27901.json
raw_json\game_franchises\game\27902.json
raw_json\game_franchises\game\27903.json
raw_json\game_franchises\game\27904.json
raw_json\game_franchises\game\27905.json
raw_json\game_franchises\game\27906.json
raw_json\game_franchises\game\27907.json
raw_json\game_franchises\game\27908.json
raw_json\game_franchises\game\2791.json
raw_json\game_franchi

raw_json\game_franchises\game\28297.json
raw_json\game_franchises\game\283.json
raw_json\game_franchises\game\2830.json
raw_json\game_franchises\game\28301.json
raw_json\game_franchises\game\28303.json
raw_json\game_franchises\game\28304.json
raw_json\game_franchises\game\28305.json
raw_json\game_franchises\game\28306.json
raw_json\game_franchises\game\28307.json
raw_json\game_franchises\game\28310.json
raw_json\game_franchises\game\28312.json
raw_json\game_franchises\game\28314.json
raw_json\game_franchises\game\28317.json
raw_json\game_franchises\game\28318.json
raw_json\game_franchises\game\2832.json
raw_json\game_franchises\game\28321.json
raw_json\game_franchises\game\28323.json
raw_json\game_franchises\game\28325.json
raw_json\game_franchises\game\28327.json
raw_json\game_franchises\game\28328.json
raw_json\game_franchises\game\28330.json
raw_json\game_franchises\game\28333.json
raw_json\game_franchises\game\28334.json
raw_json\game_franchises\game\28340.json
raw_json\game_franch

raw_json\game_franchises\game\28963.json
raw_json\game_franchises\game\28964.json
raw_json\game_franchises\game\28965.json
raw_json\game_franchises\game\28966.json
raw_json\game_franchises\game\28967.json
raw_json\game_franchises\game\28968.json
raw_json\game_franchises\game\28970.json
raw_json\game_franchises\game\28972.json
raw_json\game_franchises\game\28973.json
raw_json\game_franchises\game\28974.json
raw_json\game_franchises\game\28979.json
raw_json\game_franchises\game\2898.json
raw_json\game_franchises\game\28980.json
raw_json\game_franchises\game\28986.json
raw_json\game_franchises\game\28987.json
raw_json\game_franchises\game\2899.json
raw_json\game_franchises\game\28990.json
raw_json\game_franchises\game\28991.json
raw_json\game_franchises\game\28992.json
raw_json\game_franchises\game\28993.json
raw_json\game_franchises\game\28994.json
raw_json\game_franchises\game\28995.json
raw_json\game_franchises\game\290.json
raw_json\game_franchises\game\29001.json
raw_json\game_franch

raw_json\game_franchises\game\29332.json
raw_json\game_franchises\game\29335.json
raw_json\game_franchises\game\29336.json
raw_json\game_franchises\game\2934.json
raw_json\game_franchises\game\29341.json
raw_json\game_franchises\game\29342.json
raw_json\game_franchises\game\29344.json
raw_json\game_franchises\game\29345.json
raw_json\game_franchises\game\29353.json
raw_json\game_franchises\game\29359.json
raw_json\game_franchises\game\2936.json
raw_json\game_franchises\game\29360.json
raw_json\game_franchises\game\29369.json
raw_json\game_franchises\game\29370.json
raw_json\game_franchises\game\29371.json
raw_json\game_franchises\game\29372.json
raw_json\game_franchises\game\29376.json
raw_json\game_franchises\game\29378.json
raw_json\game_franchises\game\29380.json
raw_json\game_franchises\game\29381.json
raw_json\game_franchises\game\29383.json
raw_json\game_franchises\game\29388.json
raw_json\game_franchises\game\29395.json
raw_json\game_franchises\game\29397.json
raw_json\game_fran

raw_json\game_franchises\game\29859.json
raw_json\game_franchises\game\29860.json
raw_json\game_franchises\game\29861.json
raw_json\game_franchises\game\29862.json
raw_json\game_franchises\game\29863.json
raw_json\game_franchises\game\29864.json
raw_json\game_franchises\game\29865.json
raw_json\game_franchises\game\29867.json
raw_json\game_franchises\game\29872.json
raw_json\game_franchises\game\29874.json
raw_json\game_franchises\game\29879.json
raw_json\game_franchises\game\29882.json
raw_json\game_franchises\game\29884.json
raw_json\game_franchises\game\29887.json
raw_json\game_franchises\game\29888.json
raw_json\game_franchises\game\2989.json
raw_json\game_franchises\game\29891.json
raw_json\game_franchises\game\29894.json
raw_json\game_franchises\game\29895.json
raw_json\game_franchises\game\29896.json
raw_json\game_franchises\game\29899.json
raw_json\game_franchises\game\29901.json
raw_json\game_franchises\game\29902.json
raw_json\game_franchises\game\29907.json
raw_json\game_fra

raw_json\game_franchises\game\3034.json
raw_json\game_franchises\game\30340.json
raw_json\game_franchises\game\30344.json
raw_json\game_franchises\game\30345.json
raw_json\game_franchises\game\30346.json
raw_json\game_franchises\game\30347.json
raw_json\game_franchises\game\3035.json
raw_json\game_franchises\game\30355.json
raw_json\game_franchises\game\30356.json
raw_json\game_franchises\game\3036.json
raw_json\game_franchises\game\30361.json
raw_json\game_franchises\game\30362.json
raw_json\game_franchises\game\30364.json
raw_json\game_franchises\game\30368.json
raw_json\game_franchises\game\30369.json
raw_json\game_franchises\game\30370.json
raw_json\game_franchises\game\30372.json
raw_json\game_franchises\game\30373.json
raw_json\game_franchises\game\30374.json
raw_json\game_franchises\game\30378.json
raw_json\game_franchises\game\30379.json
raw_json\game_franchises\game\30383.json
raw_json\game_franchises\game\30384.json
raw_json\game_franchises\game\30387.json
raw_json\game_franc

raw_json\game_franchises\game\30777.json
raw_json\game_franchises\game\30786.json
raw_json\game_franchises\game\30795.json
raw_json\game_franchises\game\30796.json
raw_json\game_franchises\game\30797.json
raw_json\game_franchises\game\30798.json
raw_json\game_franchises\game\30799.json
raw_json\game_franchises\game\30800.json
raw_json\game_franchises\game\30801.json
raw_json\game_franchises\game\30803.json
raw_json\game_franchises\game\30804.json
raw_json\game_franchises\game\30806.json
raw_json\game_franchises\game\3081.json
raw_json\game_franchises\game\30811.json
raw_json\game_franchises\game\30813.json
raw_json\game_franchises\game\30819.json
raw_json\game_franchises\game\3082.json
raw_json\game_franchises\game\30820.json
raw_json\game_franchises\game\30823.json
raw_json\game_franchises\game\30825.json
raw_json\game_franchises\game\30827.json
raw_json\game_franchises\game\30828.json
raw_json\game_franchises\game\3083.json
raw_json\game_franchises\game\30836.json
raw_json\game_franc

raw_json\game_franchises\game\31250.json
raw_json\game_franchises\game\31253.json
raw_json\game_franchises\game\3126.json
raw_json\game_franchises\game\31263.json
raw_json\game_franchises\game\31264.json
raw_json\game_franchises\game\31265.json
raw_json\game_franchises\game\31266.json
raw_json\game_franchises\game\31273.json
raw_json\game_franchises\game\31275.json
raw_json\game_franchises\game\31279.json
raw_json\game_franchises\game\3128.json
raw_json\game_franchises\game\31280.json
raw_json\game_franchises\game\31281.json
raw_json\game_franchises\game\31283.json
raw_json\game_franchises\game\31284.json
raw_json\game_franchises\game\31285.json
raw_json\game_franchises\game\31286.json
raw_json\game_franchises\game\31288.json
raw_json\game_franchises\game\31289.json
raw_json\game_franchises\game\31290.json
raw_json\game_franchises\game\31294.json
raw_json\game_franchises\game\31298.json
raw_json\game_franchises\game\31299.json
raw_json\game_franchises\game\3130.json
raw_json\game_franc

raw_json\game_franchises\game\31738.json
raw_json\game_franchises\game\31739.json
raw_json\game_franchises\game\3174.json
raw_json\game_franchises\game\31740.json
raw_json\game_franchises\game\31741.json
raw_json\game_franchises\game\31742.json
raw_json\game_franchises\game\31743.json
raw_json\game_franchises\game\31744.json
raw_json\game_franchises\game\31745.json
raw_json\game_franchises\game\31747.json
raw_json\game_franchises\game\31748.json
raw_json\game_franchises\game\3175.json
raw_json\game_franchises\game\31751.json
raw_json\game_franchises\game\31752.json
raw_json\game_franchises\game\31753.json
raw_json\game_franchises\game\31754.json
raw_json\game_franchises\game\31755.json
raw_json\game_franchises\game\31757.json
raw_json\game_franchises\game\31759.json
raw_json\game_franchises\game\31760.json
raw_json\game_franchises\game\31762.json
raw_json\game_franchises\game\31763.json
raw_json\game_franchises\game\31764.json
raw_json\game_franchises\game\31766.json
raw_json\game_fran

raw_json\game_franchises\game\32197.json
raw_json\game_franchises\game\32198.json
raw_json\game_franchises\game\32199.json
raw_json\game_franchises\game\32200.json
raw_json\game_franchises\game\32201.json
raw_json\game_franchises\game\32202.json
raw_json\game_franchises\game\32203.json
raw_json\game_franchises\game\32208.json
raw_json\game_franchises\game\32210.json
raw_json\game_franchises\game\32213.json
raw_json\game_franchises\game\32214.json
raw_json\game_franchises\game\32215.json
raw_json\game_franchises\game\32217.json
raw_json\game_franchises\game\32218.json
raw_json\game_franchises\game\32219.json
raw_json\game_franchises\game\32220.json
raw_json\game_franchises\game\32221.json
raw_json\game_franchises\game\32222.json
raw_json\game_franchises\game\32223.json
raw_json\game_franchises\game\32224.json
raw_json\game_franchises\game\32225.json
raw_json\game_franchises\game\32226.json
raw_json\game_franchises\game\32227.json
raw_json\game_franchises\game\32229.json
raw_json\game_fr

raw_json\game_franchises\game\32633.json
raw_json\game_franchises\game\32636.json
raw_json\game_franchises\game\32639.json
raw_json\game_franchises\game\3264.json
raw_json\game_franchises\game\32640.json
raw_json\game_franchises\game\32645.json
raw_json\game_franchises\game\32646.json
raw_json\game_franchises\game\32647.json
raw_json\game_franchises\game\32651.json
raw_json\game_franchises\game\32655.json
raw_json\game_franchises\game\32656.json
raw_json\game_franchises\game\32658.json
raw_json\game_franchises\game\32660.json
raw_json\game_franchises\game\32661.json
raw_json\game_franchises\game\32666.json
raw_json\game_franchises\game\32668.json
raw_json\game_franchises\game\3267.json
raw_json\game_franchises\game\32673.json
raw_json\game_franchises\game\32674.json
raw_json\game_franchises\game\32675.json
raw_json\game_franchises\game\32678.json
raw_json\game_franchises\game\32679.json
raw_json\game_franchises\game\32680.json
raw_json\game_franchises\game\32681.json
raw_json\game_fran

raw_json\game_franchises\game\33085.json
raw_json\game_franchises\game\33086.json
raw_json\game_franchises\game\33088.json
raw_json\game_franchises\game\33097.json
raw_json\game_franchises\game\33098.json
raw_json\game_franchises\game\3310.json
raw_json\game_franchises\game\33100.json
raw_json\game_franchises\game\33101.json
raw_json\game_franchises\game\33106.json
raw_json\game_franchises\game\33107.json
raw_json\game_franchises\game\33108.json
raw_json\game_franchises\game\33109.json
raw_json\game_franchises\game\3311.json
raw_json\game_franchises\game\33110.json
raw_json\game_franchises\game\33113.json
raw_json\game_franchises\game\33114.json
raw_json\game_franchises\game\33115.json
raw_json\game_franchises\game\33117.json
raw_json\game_franchises\game\33118.json
raw_json\game_franchises\game\3312.json
raw_json\game_franchises\game\33128.json
raw_json\game_franchises\game\33129.json
raw_json\game_franchises\game\33131.json
raw_json\game_franchises\game\33134.json
raw_json\game_franc

raw_json\game_franchises\game\33572.json
raw_json\game_franchises\game\33573.json
raw_json\game_franchises\game\33574.json
raw_json\game_franchises\game\33576.json
raw_json\game_franchises\game\33577.json
raw_json\game_franchises\game\33578.json
raw_json\game_franchises\game\33579.json
raw_json\game_franchises\game\3358.json
raw_json\game_franchises\game\33580.json
raw_json\game_franchises\game\33581.json
raw_json\game_franchises\game\33584.json
raw_json\game_franchises\game\33585.json
raw_json\game_franchises\game\33587.json
raw_json\game_franchises\game\3359.json
raw_json\game_franchises\game\33591.json
raw_json\game_franchises\game\33593.json
raw_json\game_franchises\game\3360.json
raw_json\game_franchises\game\33602.json
raw_json\game_franchises\game\33606.json
raw_json\game_franchises\game\33617.json
raw_json\game_franchises\game\33620.json
raw_json\game_franchises\game\33627.json
raw_json\game_franchises\game\33636.json
raw_json\game_franchises\game\33639.json
raw_json\game_franc

raw_json\game_franchises\game\33999.json
raw_json\game_franchises\game\34.json
raw_json\game_franchises\game\340.json
raw_json\game_franchises\game\34013.json
raw_json\game_franchises\game\34016.json
raw_json\game_franchises\game\34017.json
raw_json\game_franchises\game\34018.json
raw_json\game_franchises\game\3402.json
raw_json\game_franchises\game\34026.json
raw_json\game_franchises\game\34027.json
raw_json\game_franchises\game\34028.json
raw_json\game_franchises\game\34029.json
raw_json\game_franchises\game\34030.json
raw_json\game_franchises\game\34035.json
raw_json\game_franchises\game\34037.json
raw_json\game_franchises\game\34038.json
raw_json\game_franchises\game\34039.json
raw_json\game_franchises\game\3404.json
raw_json\game_franchises\game\34040.json
raw_json\game_franchises\game\34041.json
raw_json\game_franchises\game\34043.json
raw_json\game_franchises\game\34049.json
raw_json\game_franchises\game\34051.json
raw_json\game_franchises\game\34058.json
raw_json\game_franchise

raw_json\game_franchises\game\34497.json
raw_json\game_franchises\game\34499.json
raw_json\game_franchises\game\3450.json
raw_json\game_franchises\game\34503.json
raw_json\game_franchises\game\34505.json
raw_json\game_franchises\game\34507.json
raw_json\game_franchises\game\3451.json
raw_json\game_franchises\game\34510.json
raw_json\game_franchises\game\34511.json
raw_json\game_franchises\game\34512.json
raw_json\game_franchises\game\34513.json
raw_json\game_franchises\game\34514.json
raw_json\game_franchises\game\3452.json
raw_json\game_franchises\game\34520.json
raw_json\game_franchises\game\34522.json
raw_json\game_franchises\game\34528.json
raw_json\game_franchises\game\34529.json
raw_json\game_franchises\game\34530.json
raw_json\game_franchises\game\34532.json
raw_json\game_franchises\game\34533.json
raw_json\game_franchises\game\34535.json
raw_json\game_franchises\game\34536.json
raw_json\game_franchises\game\34537.json
raw_json\game_franchises\game\34538.json
raw_json\game_franc

raw_json\game_franchises\game\34975.json
raw_json\game_franchises\game\34976.json
raw_json\game_franchises\game\34977.json
raw_json\game_franchises\game\34978.json
raw_json\game_franchises\game\34984.json
raw_json\game_franchises\game\34986.json
raw_json\game_franchises\game\34987.json
raw_json\game_franchises\game\34988.json
raw_json\game_franchises\game\34990.json
raw_json\game_franchises\game\34991.json
raw_json\game_franchises\game\34997.json
raw_json\game_franchises\game\34999.json
raw_json\game_franchises\game\350.json
raw_json\game_franchises\game\35001.json
raw_json\game_franchises\game\35002.json
raw_json\game_franchises\game\35003.json
raw_json\game_franchises\game\35004.json
raw_json\game_franchises\game\35005.json
raw_json\game_franchises\game\35006.json
raw_json\game_franchises\game\35007.json
raw_json\game_franchises\game\35008.json
raw_json\game_franchises\game\35009.json
raw_json\game_franchises\game\3501.json
raw_json\game_franchises\game\35010.json
raw_json\game_franc

raw_json\game_franchises\game\35510.json
raw_json\game_franchises\game\35511.json
raw_json\game_franchises\game\35513.json
raw_json\game_franchises\game\35514.json
raw_json\game_franchises\game\35517.json
raw_json\game_franchises\game\3552.json
raw_json\game_franchises\game\35520.json
raw_json\game_franchises\game\35521.json
raw_json\game_franchises\game\35523.json
raw_json\game_franchises\game\3553.json
raw_json\game_franchises\game\35530.json
raw_json\game_franchises\game\35531.json
raw_json\game_franchises\game\35532.json
raw_json\game_franchises\game\35533.json
raw_json\game_franchises\game\35536.json
raw_json\game_franchises\game\35537.json
raw_json\game_franchises\game\35539.json
raw_json\game_franchises\game\3554.json
raw_json\game_franchises\game\35541.json
raw_json\game_franchises\game\35546.json
raw_json\game_franchises\game\35549.json
raw_json\game_franchises\game\3555.json
raw_json\game_franchises\game\35552.json
raw_json\game_franchises\game\35553.json
raw_json\game_franch

raw_json\game_franchises\game\35964.json
raw_json\game_franchises\game\35965.json
raw_json\game_franchises\game\35970.json
raw_json\game_franchises\game\35971.json
raw_json\game_franchises\game\35972.json
raw_json\game_franchises\game\35973.json
raw_json\game_franchises\game\35975.json
raw_json\game_franchises\game\35978.json
raw_json\game_franchises\game\35979.json
raw_json\game_franchises\game\35980.json
raw_json\game_franchises\game\35982.json
raw_json\game_franchises\game\35988.json
raw_json\game_franchises\game\35989.json
raw_json\game_franchises\game\3599.json
raw_json\game_franchises\game\35990.json
raw_json\game_franchises\game\35995.json
raw_json\game_franchises\game\35997.json
raw_json\game_franchises\game\360.json
raw_json\game_franchises\game\36000.json
raw_json\game_franchises\game\36006.json
raw_json\game_franchises\game\3602.json
raw_json\game_franchises\game\36021.json
raw_json\game_franchises\game\36024.json
raw_json\game_franchises\game\36025.json
raw_json\game_franch

raw_json\game_franchises\game\36448.json
raw_json\game_franchises\game\36449.json
raw_json\game_franchises\game\3645.json
raw_json\game_franchises\game\36453.json
raw_json\game_franchises\game\36454.json
raw_json\game_franchises\game\36456.json
raw_json\game_franchises\game\36462.json
raw_json\game_franchises\game\36463.json
raw_json\game_franchises\game\36465.json
raw_json\game_franchises\game\36469.json
raw_json\game_franchises\game\3647.json
raw_json\game_franchises\game\36470.json
raw_json\game_franchises\game\36480.json
raw_json\game_franchises\game\36481.json
raw_json\game_franchises\game\36484.json
raw_json\game_franchises\game\36486.json
raw_json\game_franchises\game\36487.json
raw_json\game_franchises\game\36488.json
raw_json\game_franchises\game\36490.json
raw_json\game_franchises\game\36493.json
raw_json\game_franchises\game\36494.json
raw_json\game_franchises\game\36495.json
raw_json\game_franchises\game\36496.json
raw_json\game_franchises\game\36497.json
raw_json\game_fran

raw_json\game_franchises\game\36889.json
raw_json\game_franchises\game\36890.json
raw_json\game_franchises\game\36891.json
raw_json\game_franchises\game\36898.json
raw_json\game_franchises\game\369.json
raw_json\game_franchises\game\36900.json
raw_json\game_franchises\game\36902.json
raw_json\game_franchises\game\36904.json
raw_json\game_franchises\game\36911.json
raw_json\game_franchises\game\36916.json
raw_json\game_franchises\game\3692.json
raw_json\game_franchises\game\36920.json
raw_json\game_franchises\game\36924.json
raw_json\game_franchises\game\36926.json
raw_json\game_franchises\game\36929.json
raw_json\game_franchises\game\3693.json
raw_json\game_franchises\game\36934.json
raw_json\game_franchises\game\36935.json
raw_json\game_franchises\game\36938.json
raw_json\game_franchises\game\36941.json
raw_json\game_franchises\game\36942.json
raw_json\game_franchises\game\36947.json
raw_json\game_franchises\game\36948.json
raw_json\game_franchises\game\36949.json
raw_json\game_franch

raw_json\game_franchises\game\37347.json
raw_json\game_franchises\game\3735.json
raw_json\game_franchises\game\37354.json
raw_json\game_franchises\game\37355.json
raw_json\game_franchises\game\37357.json
raw_json\game_franchises\game\37361.json
raw_json\game_franchises\game\37362.json
raw_json\game_franchises\game\37363.json
raw_json\game_franchises\game\37367.json
raw_json\game_franchises\game\37368.json
raw_json\game_franchises\game\37369.json
raw_json\game_franchises\game\37370.json
raw_json\game_franchises\game\37378.json
raw_json\game_franchises\game\3738.json
raw_json\game_franchises\game\37382.json
raw_json\game_franchises\game\37383.json
raw_json\game_franchises\game\37385.json
raw_json\game_franchises\game\3739.json
raw_json\game_franchises\game\37397.json
raw_json\game_franchises\game\374.json
raw_json\game_franchises\game\3740.json
raw_json\game_franchises\game\37401.json
raw_json\game_franchises\game\37406.json
raw_json\game_franchises\game\37410.json
raw_json\game_franchis

raw_json\game_franchises\game\37802.json
raw_json\game_franchises\game\37804.json
raw_json\game_franchises\game\37807.json
raw_json\game_franchises\game\3781.json
raw_json\game_franchises\game\37813.json
raw_json\game_franchises\game\37814.json
raw_json\game_franchises\game\37819.json
raw_json\game_franchises\game\37820.json
raw_json\game_franchises\game\37821.json
raw_json\game_franchises\game\37822.json
raw_json\game_franchises\game\37825.json
raw_json\game_franchises\game\37826.json
raw_json\game_franchises\game\37827.json
raw_json\game_franchises\game\37828.json
raw_json\game_franchises\game\37829.json
raw_json\game_franchises\game\3783.json
raw_json\game_franchises\game\37830.json
raw_json\game_franchises\game\37832.json
raw_json\game_franchises\game\37833.json
raw_json\game_franchises\game\37834.json
raw_json\game_franchises\game\37835.json
raw_json\game_franchises\game\37836.json
raw_json\game_franchises\game\37837.json
raw_json\game_franchises\game\3784.json
raw_json\game_franc

raw_json\game_franchises\game\3823.json
raw_json\game_franchises\game\38231.json
raw_json\game_franchises\game\38232.json
raw_json\game_franchises\game\38233.json
raw_json\game_franchises\game\38236.json
raw_json\game_franchises\game\38237.json
raw_json\game_franchises\game\38238.json
raw_json\game_franchises\game\38239.json
raw_json\game_franchises\game\38240.json
raw_json\game_franchises\game\38243.json
raw_json\game_franchises\game\38244.json
raw_json\game_franchises\game\38245.json
raw_json\game_franchises\game\38246.json
raw_json\game_franchises\game\38247.json
raw_json\game_franchises\game\38248.json
raw_json\game_franchises\game\38249.json
raw_json\game_franchises\game\38250.json
raw_json\game_franchises\game\38251.json
raw_json\game_franchises\game\38252.json
raw_json\game_franchises\game\38255.json
raw_json\game_franchises\game\38259.json
raw_json\game_franchises\game\3826.json
raw_json\game_franchises\game\38260.json
raw_json\game_franchises\game\38261.json
raw_json\game_fran

raw_json\game_franchises\game\38672.json
raw_json\game_franchises\game\38673.json
raw_json\game_franchises\game\38674.json
raw_json\game_franchises\game\38675.json
raw_json\game_franchises\game\38676.json
raw_json\game_franchises\game\38677.json
raw_json\game_franchises\game\38679.json
raw_json\game_franchises\game\38680.json
raw_json\game_franchises\game\38681.json
raw_json\game_franchises\game\38683.json
raw_json\game_franchises\game\38684.json
raw_json\game_franchises\game\38685.json
raw_json\game_franchises\game\38686.json
raw_json\game_franchises\game\38688.json
raw_json\game_franchises\game\3869.json
raw_json\game_franchises\game\38694.json
raw_json\game_franchises\game\38696.json
raw_json\game_franchises\game\38697.json
raw_json\game_franchises\game\38707.json
raw_json\game_franchises\game\38709.json
raw_json\game_franchises\game\3871.json
raw_json\game_franchises\game\38712.json
raw_json\game_franchises\game\38713.json
raw_json\game_franchises\game\38714.json
raw_json\game_fran

raw_json\game_franchises\game\39107.json
raw_json\game_franchises\game\3911.json
raw_json\game_franchises\game\39116.json
raw_json\game_franchises\game\3912.json
raw_json\game_franchises\game\39121.json
raw_json\game_franchises\game\39122.json
raw_json\game_franchises\game\39123.json
raw_json\game_franchises\game\39125.json
raw_json\game_franchises\game\39126.json
raw_json\game_franchises\game\39127.json
raw_json\game_franchises\game\3913.json
raw_json\game_franchises\game\39130.json
raw_json\game_franchises\game\39139.json
raw_json\game_franchises\game\3914.json
raw_json\game_franchises\game\39140.json
raw_json\game_franchises\game\39142.json
raw_json\game_franchises\game\39144.json
raw_json\game_franchises\game\39145.json
raw_json\game_franchises\game\39146.json
raw_json\game_franchises\game\39152.json
raw_json\game_franchises\game\39155.json
raw_json\game_franchises\game\39156.json
raw_json\game_franchises\game\39159.json
raw_json\game_franchises\game\3916.json
raw_json\game_franchi

raw_json\game_franchises\game\3954.json
raw_json\game_franchises\game\39540.json
raw_json\game_franchises\game\39541.json
raw_json\game_franchises\game\39542.json
raw_json\game_franchises\game\39543.json
raw_json\game_franchises\game\39544.json
raw_json\game_franchises\game\39547.json
raw_json\game_franchises\game\39555.json
raw_json\game_franchises\game\39556.json
raw_json\game_franchises\game\3956.json
raw_json\game_franchises\game\39562.json
raw_json\game_franchises\game\39565.json
raw_json\game_franchises\game\39566.json
raw_json\game_franchises\game\39568.json
raw_json\game_franchises\game\39570.json
raw_json\game_franchises\game\39571.json
raw_json\game_franchises\game\39572.json
raw_json\game_franchises\game\39575.json
raw_json\game_franchises\game\39577.json
raw_json\game_franchises\game\39579.json
raw_json\game_franchises\game\39580.json
raw_json\game_franchises\game\39587.json
raw_json\game_franchises\game\39588.json
raw_json\game_franchises\game\39590.json
raw_json\game_fran

raw_json\game_franchises\game\39988.json
raw_json\game_franchises\game\39989.json
raw_json\game_franchises\game\39991.json
raw_json\game_franchises\game\39992.json
raw_json\game_franchises\game\39993.json
raw_json\game_franchises\game\39994.json
raw_json\game_franchises\game\39995.json
raw_json\game_franchises\game\39996.json
raw_json\game_franchises\game\39997.json
raw_json\game_franchises\game\39998.json
raw_json\game_franchises\game\39999.json
raw_json\game_franchises\game\4.json
raw_json\game_franchises\game\400.json
raw_json\game_franchises\game\4000.json
raw_json\game_franchises\game\40000.json
raw_json\game_franchises\game\40005.json
raw_json\game_franchises\game\40006.json
raw_json\game_franchises\game\40007.json
raw_json\game_franchises\game\4001.json
raw_json\game_franchises\game\40010.json
raw_json\game_franchises\game\40012.json
raw_json\game_franchises\game\40020.json
raw_json\game_franchises\game\40023.json
raw_json\game_franchises\game\40026.json
raw_json\game_franchises

raw_json\game_franchises\game\40379.json
raw_json\game_franchises\game\40383.json
raw_json\game_franchises\game\40384.json
raw_json\game_franchises\game\40387.json
raw_json\game_franchises\game\40388.json
raw_json\game_franchises\game\40389.json
raw_json\game_franchises\game\40390.json
raw_json\game_franchises\game\40391.json
raw_json\game_franchises\game\40392.json
raw_json\game_franchises\game\40393.json
raw_json\game_franchises\game\40396.json
raw_json\game_franchises\game\40399.json
raw_json\game_franchises\game\404.json
raw_json\game_franchises\game\40404.json
raw_json\game_franchises\game\40405.json
raw_json\game_franchises\game\40407.json
raw_json\game_franchises\game\40408.json
raw_json\game_franchises\game\40413.json
raw_json\game_franchises\game\40416.json
raw_json\game_franchises\game\40417.json
raw_json\game_franchises\game\40419.json
raw_json\game_franchises\game\40421.json
raw_json\game_franchises\game\40423.json
raw_json\game_franchises\game\40424.json
raw_json\game_fran

raw_json\game_franchises\game\41246.json
raw_json\game_franchises\game\41247.json
raw_json\game_franchises\game\41248.json
raw_json\game_franchises\game\41249.json
raw_json\game_franchises\game\4125.json
raw_json\game_franchises\game\41252.json
raw_json\game_franchises\game\41257.json
raw_json\game_franchises\game\41259.json
raw_json\game_franchises\game\41261.json
raw_json\game_franchises\game\41262.json
raw_json\game_franchises\game\41263.json
raw_json\game_franchises\game\41266.json
raw_json\game_franchises\game\41267.json
raw_json\game_franchises\game\41276.json
raw_json\game_franchises\game\41278.json
raw_json\game_franchises\game\41279.json
raw_json\game_franchises\game\4128.json
raw_json\game_franchises\game\41280.json
raw_json\game_franchises\game\41282.json
raw_json\game_franchises\game\41283.json
raw_json\game_franchises\game\41284.json
raw_json\game_franchises\game\41285.json
raw_json\game_franchises\game\41286.json
raw_json\game_franchises\game\41287.json
raw_json\game_fran

raw_json\game_franchises\game\41757.json
raw_json\game_franchises\game\41759.json
raw_json\game_franchises\game\4176.json
raw_json\game_franchises\game\41761.json
raw_json\game_franchises\game\41762.json
raw_json\game_franchises\game\41763.json
raw_json\game_franchises\game\4177.json
raw_json\game_franchises\game\41770.json
raw_json\game_franchises\game\41774.json
raw_json\game_franchises\game\41779.json
raw_json\game_franchises\game\4178.json
raw_json\game_franchises\game\41785.json
raw_json\game_franchises\game\41788.json
raw_json\game_franchises\game\41795.json
raw_json\game_franchises\game\41797.json
raw_json\game_franchises\game\41802.json
raw_json\game_franchises\game\41807.json
raw_json\game_franchises\game\4181.json
raw_json\game_franchises\game\4183.json
raw_json\game_franchises\game\41830.json
raw_json\game_franchises\game\41836.json
raw_json\game_franchises\game\4184.json
raw_json\game_franchises\game\41840.json
raw_json\game_franchises\game\41841.json
raw_json\game_franchis

raw_json\game_franchises\game\42202.json
raw_json\game_franchises\game\42206.json
raw_json\game_franchises\game\42210.json
raw_json\game_franchises\game\42211.json
raw_json\game_franchises\game\42212.json
raw_json\game_franchises\game\42216.json
raw_json\game_franchises\game\4222.json
raw_json\game_franchises\game\42227.json
raw_json\game_franchises\game\42228.json
raw_json\game_franchises\game\42237.json
raw_json\game_franchises\game\42241.json
raw_json\game_franchises\game\42242.json
raw_json\game_franchises\game\42243.json
raw_json\game_franchises\game\42244.json
raw_json\game_franchises\game\42245.json
raw_json\game_franchises\game\42246.json
raw_json\game_franchises\game\42247.json
raw_json\game_franchises\game\42248.json
raw_json\game_franchises\game\42249.json
raw_json\game_franchises\game\4225.json
raw_json\game_franchises\game\42250.json
raw_json\game_franchises\game\42251.json
raw_json\game_franchises\game\42257.json
raw_json\game_franchises\game\42259.json
raw_json\game_fran

raw_json\game_franchises\game\42713.json
raw_json\game_franchises\game\42715.json
raw_json\game_franchises\game\42717.json
raw_json\game_franchises\game\4272.json
raw_json\game_franchises\game\42729.json
raw_json\game_franchises\game\4273.json
raw_json\game_franchises\game\42730.json
raw_json\game_franchises\game\42731.json
raw_json\game_franchises\game\42732.json
raw_json\game_franchises\game\42736.json
raw_json\game_franchises\game\4274.json
raw_json\game_franchises\game\42742.json
raw_json\game_franchises\game\42743.json
raw_json\game_franchises\game\42746.json
raw_json\game_franchises\game\42747.json
raw_json\game_franchises\game\42748.json
raw_json\game_franchises\game\42753.json
raw_json\game_franchises\game\42758.json
raw_json\game_franchises\game\42760.json
raw_json\game_franchises\game\42761.json
raw_json\game_franchises\game\42763.json
raw_json\game_franchises\game\42764.json
raw_json\game_franchises\game\4277.json
raw_json\game_franchises\game\42776.json
raw_json\game_franch

raw_json\game_franchises\game\43171.json
raw_json\game_franchises\game\43174.json
raw_json\game_franchises\game\43175.json
raw_json\game_franchises\game\43177.json
raw_json\game_franchises\game\43178.json
raw_json\game_franchises\game\43179.json
raw_json\game_franchises\game\4318.json
raw_json\game_franchises\game\43184.json
raw_json\game_franchises\game\43185.json
raw_json\game_franchises\game\43186.json
raw_json\game_franchises\game\43187.json
raw_json\game_franchises\game\4319.json
raw_json\game_franchises\game\432.json
raw_json\game_franchises\game\43205.json
raw_json\game_franchises\game\43207.json
raw_json\game_franchises\game\43212.json
raw_json\game_franchises\game\43215.json
raw_json\game_franchises\game\43216.json
raw_json\game_franchises\game\43217.json
raw_json\game_franchises\game\43218.json
raw_json\game_franchises\game\43219.json
raw_json\game_franchises\game\43220.json
raw_json\game_franchises\game\43226.json
raw_json\game_franchises\game\43233.json
raw_json\game_franch

raw_json\game_franchises\game\43725.json
raw_json\game_franchises\game\43727.json
raw_json\game_franchises\game\43731.json
raw_json\game_franchises\game\43736.json
raw_json\game_franchises\game\43737.json
raw_json\game_franchises\game\43746.json
raw_json\game_franchises\game\43747.json
raw_json\game_franchises\game\43748.json
raw_json\game_franchises\game\43749.json
raw_json\game_franchises\game\43761.json
raw_json\game_franchises\game\43768.json
raw_json\game_franchises\game\43774.json
raw_json\game_franchises\game\43775.json
raw_json\game_franchises\game\43781.json
raw_json\game_franchises\game\43783.json
raw_json\game_franchises\game\4379.json
raw_json\game_franchises\game\43790.json
raw_json\game_franchises\game\43801.json
raw_json\game_franchises\game\43802.json
raw_json\game_franchises\game\43804.json
raw_json\game_franchises\game\4381.json
raw_json\game_franchises\game\43811.json
raw_json\game_franchises\game\43813.json
raw_json\game_franchises\game\43816.json
raw_json\game_fran

raw_json\game_franchises\game\44244.json
raw_json\game_franchises\game\44251.json
raw_json\game_franchises\game\44253.json
raw_json\game_franchises\game\44254.json
raw_json\game_franchises\game\44255.json
raw_json\game_franchises\game\44256.json
raw_json\game_franchises\game\4426.json
raw_json\game_franchises\game\44260.json
raw_json\game_franchises\game\44261.json
raw_json\game_franchises\game\44262.json
raw_json\game_franchises\game\44263.json
raw_json\game_franchises\game\44264.json
raw_json\game_franchises\game\44268.json
raw_json\game_franchises\game\44274.json
raw_json\game_franchises\game\44275.json
raw_json\game_franchises\game\44277.json
raw_json\game_franchises\game\44279.json
raw_json\game_franchises\game\44285.json
raw_json\game_franchises\game\44287.json
raw_json\game_franchises\game\44288.json
raw_json\game_franchises\game\44289.json
raw_json\game_franchises\game\4429.json
raw_json\game_franchises\game\44293.json
raw_json\game_franchises\game\44296.json
raw_json\game_fran

raw_json\game_franchises\game\44784.json
raw_json\game_franchises\game\44785.json
raw_json\game_franchises\game\44786.json
raw_json\game_franchises\game\4480.json
raw_json\game_franchises\game\44802.json
raw_json\game_franchises\game\44809.json
raw_json\game_franchises\game\4481.json
raw_json\game_franchises\game\44813.json
raw_json\game_franchises\game\44814.json
raw_json\game_franchises\game\44818.json
raw_json\game_franchises\game\44819.json
raw_json\game_franchises\game\4482.json
raw_json\game_franchises\game\44820.json
raw_json\game_franchises\game\44821.json
raw_json\game_franchises\game\44822.json
raw_json\game_franchises\game\44824.json
raw_json\game_franchises\game\44827.json
raw_json\game_franchises\game\44828.json
raw_json\game_franchises\game\44830.json
raw_json\game_franchises\game\44831.json
raw_json\game_franchises\game\44834.json
raw_json\game_franchises\game\44835.json
raw_json\game_franchises\game\44836.json
raw_json\game_franchises\game\44837.json
raw_json\game_franc

raw_json\game_franchises\game\45298.json
raw_json\game_franchises\game\453.json
raw_json\game_franchises\game\4530.json
raw_json\game_franchises\game\45304.json
raw_json\game_franchises\game\45315.json
raw_json\game_franchises\game\45317.json
raw_json\game_franchises\game\45318.json
raw_json\game_franchises\game\45331.json
raw_json\game_franchises\game\45333.json
raw_json\game_franchises\game\45334.json
raw_json\game_franchises\game\45337.json
raw_json\game_franchises\game\4534.json
raw_json\game_franchises\game\45341.json
raw_json\game_franchises\game\45343.json
raw_json\game_franchises\game\45344.json
raw_json\game_franchises\game\45349.json
raw_json\game_franchises\game\4535.json
raw_json\game_franchises\game\45352.json
raw_json\game_franchises\game\45354.json
raw_json\game_franchises\game\45356.json
raw_json\game_franchises\game\45357.json
raw_json\game_franchises\game\45359.json
raw_json\game_franchises\game\4536.json
raw_json\game_franchises\game\45364.json
raw_json\game_franchis

raw_json\game_franchises\game\45810.json
raw_json\game_franchises\game\45811.json
raw_json\game_franchises\game\45813.json
raw_json\game_franchises\game\45815.json
raw_json\game_franchises\game\45816.json
raw_json\game_franchises\game\45818.json
raw_json\game_franchises\game\4582.json
raw_json\game_franchises\game\45822.json
raw_json\game_franchises\game\45823.json
raw_json\game_franchises\game\45824.json
raw_json\game_franchises\game\45825.json
raw_json\game_franchises\game\45826.json
raw_json\game_franchises\game\45827.json
raw_json\game_franchises\game\45828.json
raw_json\game_franchises\game\45829.json
raw_json\game_franchises\game\4583.json
raw_json\game_franchises\game\45830.json
raw_json\game_franchises\game\45832.json
raw_json\game_franchises\game\45833.json
raw_json\game_franchises\game\45834.json
raw_json\game_franchises\game\45836.json
raw_json\game_franchises\game\45837.json
raw_json\game_franchises\game\45839.json
raw_json\game_franchises\game\45840.json
raw_json\game_fran

raw_json\game_franchises\game\46333.json
raw_json\game_franchises\game\46334.json
raw_json\game_franchises\game\46335.json
raw_json\game_franchises\game\46336.json
raw_json\game_franchises\game\46337.json
raw_json\game_franchises\game\46338.json
raw_json\game_franchises\game\46339.json
raw_json\game_franchises\game\4634.json
raw_json\game_franchises\game\46344.json
raw_json\game_franchises\game\46345.json
raw_json\game_franchises\game\46346.json
raw_json\game_franchises\game\46347.json
raw_json\game_franchises\game\46348.json
raw_json\game_franchises\game\46349.json
raw_json\game_franchises\game\4635.json
raw_json\game_franchises\game\46350.json
raw_json\game_franchises\game\46351.json
raw_json\game_franchises\game\46356.json
raw_json\game_franchises\game\46359.json
raw_json\game_franchises\game\4636.json
raw_json\game_franchises\game\46361.json
raw_json\game_franchises\game\46364.json
raw_json\game_franchises\game\46365.json
raw_json\game_franchises\game\4637.json
raw_json\game_franch

raw_json\game_franchises\game\46766.json
raw_json\game_franchises\game\46767.json
raw_json\game_franchises\game\46769.json
raw_json\game_franchises\game\46770.json
raw_json\game_franchises\game\46771.json
raw_json\game_franchises\game\46776.json
raw_json\game_franchises\game\46777.json
raw_json\game_franchises\game\4678.json
raw_json\game_franchises\game\46780.json
raw_json\game_franchises\game\46788.json
raw_json\game_franchises\game\46790.json
raw_json\game_franchises\game\46792.json
raw_json\game_franchises\game\46796.json
raw_json\game_franchises\game\46797.json
raw_json\game_franchises\game\46799.json
raw_json\game_franchises\game\4680.json
raw_json\game_franchises\game\46800.json
raw_json\game_franchises\game\46801.json
raw_json\game_franchises\game\46803.json
raw_json\game_franchises\game\46804.json
raw_json\game_franchises\game\46806.json
raw_json\game_franchises\game\46808.json
raw_json\game_franchises\game\46809.json
raw_json\game_franchises\game\46810.json
raw_json\game_fran

raw_json\game_franchises\game\47302.json
raw_json\game_franchises\game\47305.json
raw_json\game_franchises\game\47308.json
raw_json\game_franchises\game\47316.json
raw_json\game_franchises\game\47319.json
raw_json\game_franchises\game\47321.json
raw_json\game_franchises\game\47328.json
raw_json\game_franchises\game\47329.json
raw_json\game_franchises\game\47330.json
raw_json\game_franchises\game\47341.json
raw_json\game_franchises\game\47342.json
raw_json\game_franchises\game\47348.json
raw_json\game_franchises\game\4735.json
raw_json\game_franchises\game\47350.json
raw_json\game_franchises\game\47352.json
raw_json\game_franchises\game\47353.json
raw_json\game_franchises\game\47354.json
raw_json\game_franchises\game\47356.json
raw_json\game_franchises\game\47358.json
raw_json\game_franchises\game\47359.json
raw_json\game_franchises\game\4736.json
raw_json\game_franchises\game\47363.json
raw_json\game_franchises\game\47364.json
raw_json\game_franchises\game\47365.json
raw_json\game_fran

raw_json\game_franchises\game\47783.json
raw_json\game_franchises\game\47791.json
raw_json\game_franchises\game\47792.json
raw_json\game_franchises\game\47796.json
raw_json\game_franchises\game\47798.json
raw_json\game_franchises\game\478.json
raw_json\game_franchises\game\47802.json
raw_json\game_franchises\game\47803.json
raw_json\game_franchises\game\47807.json
raw_json\game_franchises\game\47809.json
raw_json\game_franchises\game\47811.json
raw_json\game_franchises\game\47814.json
raw_json\game_franchises\game\47816.json
raw_json\game_franchises\game\47818.json
raw_json\game_franchises\game\47821.json
raw_json\game_franchises\game\47823.json
raw_json\game_franchises\game\47824.json
raw_json\game_franchises\game\47826.json
raw_json\game_franchises\game\47827.json
raw_json\game_franchises\game\47828.json
raw_json\game_franchises\game\47829.json
raw_json\game_franchises\game\47830.json
raw_json\game_franchises\game\47831.json
raw_json\game_franchises\game\47837.json
raw_json\game_fran

raw_json\game_franchises\game\48357.json
raw_json\game_franchises\game\48358.json
raw_json\game_franchises\game\48359.json
raw_json\game_franchises\game\48363.json
raw_json\game_franchises\game\48367.json
raw_json\game_franchises\game\48371.json
raw_json\game_franchises\game\48376.json
raw_json\game_franchises\game\48381.json
raw_json\game_franchises\game\48382.json
raw_json\game_franchises\game\48383.json
raw_json\game_franchises\game\48389.json
raw_json\game_franchises\game\48390.json
raw_json\game_franchises\game\48395.json
raw_json\game_franchises\game\48399.json
raw_json\game_franchises\game\4840.json
raw_json\game_franchises\game\48400.json
raw_json\game_franchises\game\48401.json
raw_json\game_franchises\game\48402.json
raw_json\game_franchises\game\48404.json
raw_json\game_franchises\game\48407.json
raw_json\game_franchises\game\48409.json
raw_json\game_franchises\game\48411.json
raw_json\game_franchises\game\48412.json
raw_json\game_franchises\game\48413.json
raw_json\game_fra

raw_json\game_franchises\game\48930.json
raw_json\game_franchises\game\48934.json
raw_json\game_franchises\game\48937.json
raw_json\game_franchises\game\4894.json
raw_json\game_franchises\game\48945.json
raw_json\game_franchises\game\48948.json
raw_json\game_franchises\game\48951.json
raw_json\game_franchises\game\48955.json
raw_json\game_franchises\game\48959.json
raw_json\game_franchises\game\4896.json
raw_json\game_franchises\game\48960.json
raw_json\game_franchises\game\48961.json
raw_json\game_franchises\game\48964.json
raw_json\game_franchises\game\48965.json
raw_json\game_franchises\game\48984.json
raw_json\game_franchises\game\48993.json
raw_json\game_franchises\game\48998.json
raw_json\game_franchises\game\49001.json
raw_json\game_franchises\game\49002.json
raw_json\game_franchises\game\49003.json
raw_json\game_franchises\game\49004.json
raw_json\game_franchises\game\49005.json
raw_json\game_franchises\game\49014.json
raw_json\game_franchises\game\49015.json
raw_json\game_fran

raw_json\game_franchises\game\49515.json
raw_json\game_franchises\game\49516.json
raw_json\game_franchises\game\49517.json
raw_json\game_franchises\game\49518.json
raw_json\game_franchises\game\49520.json
raw_json\game_franchises\game\49521.json
raw_json\game_franchises\game\49523.json
raw_json\game_franchises\game\49524.json
raw_json\game_franchises\game\49529.json
raw_json\game_franchises\game\49533.json
raw_json\game_franchises\game\49542.json
raw_json\game_franchises\game\49550.json
raw_json\game_franchises\game\49553.json
raw_json\game_franchises\game\49556.json
raw_json\game_franchises\game\49557.json
raw_json\game_franchises\game\49558.json
raw_json\game_franchises\game\49561.json
raw_json\game_franchises\game\49562.json
raw_json\game_franchises\game\49564.json
raw_json\game_franchises\game\49565.json
raw_json\game_franchises\game\49569.json
raw_json\game_franchises\game\4957.json
raw_json\game_franchises\game\49574.json
raw_json\game_franchises\game\49583.json
raw_json\game_fra

raw_json\game_franchises\game\50091.json
raw_json\game_franchises\game\50099.json
raw_json\game_franchises\game\5010.json
raw_json\game_franchises\game\50100.json
raw_json\game_franchises\game\50101.json
raw_json\game_franchises\game\50102.json
raw_json\game_franchises\game\50105.json
raw_json\game_franchises\game\50106.json
raw_json\game_franchises\game\50107.json
raw_json\game_franchises\game\5011.json
raw_json\game_franchises\game\50111.json
raw_json\game_franchises\game\5012.json
raw_json\game_franchises\game\50138.json
raw_json\game_franchises\game\50153.json
raw_json\game_franchises\game\50154.json
raw_json\game_franchises\game\50155.json
raw_json\game_franchises\game\50156.json
raw_json\game_franchises\game\50157.json
raw_json\game_franchises\game\50159.json
raw_json\game_franchises\game\5016.json
raw_json\game_franchises\game\50160.json
raw_json\game_franchises\game\50161.json
raw_json\game_franchises\game\50162.json
raw_json\game_franchises\game\50165.json
raw_json\game_franch

raw_json\game_franchises\game\50759.json
raw_json\game_franchises\game\50760.json
raw_json\game_franchises\game\50762.json
raw_json\game_franchises\game\50763.json
raw_json\game_franchises\game\50764.json
raw_json\game_franchises\game\50767.json
raw_json\game_franchises\game\50776.json
raw_json\game_franchises\game\50789.json
raw_json\game_franchises\game\5079.json
raw_json\game_franchises\game\50791.json
raw_json\game_franchises\game\50799.json
raw_json\game_franchises\game\508.json
raw_json\game_franchises\game\5080.json
raw_json\game_franchises\game\50800.json
raw_json\game_franchises\game\50803.json
raw_json\game_franchises\game\50806.json
raw_json\game_franchises\game\50807.json
raw_json\game_franchises\game\50808.json
raw_json\game_franchises\game\50810.json
raw_json\game_franchises\game\50811.json
raw_json\game_franchises\game\50816.json
raw_json\game_franchises\game\5082.json
raw_json\game_franchises\game\5083.json
raw_json\game_franchises\game\50835.json
raw_json\game_franchis

raw_json\game_franchises\game\51454.json
raw_json\game_franchises\game\51457.json
raw_json\game_franchises\game\51459.json
raw_json\game_franchises\game\5146.json
raw_json\game_franchises\game\51460.json
raw_json\game_franchises\game\51461.json
raw_json\game_franchises\game\51464.json
raw_json\game_franchises\game\51465.json
raw_json\game_franchises\game\51466.json
raw_json\game_franchises\game\51469.json
raw_json\game_franchises\game\51470.json
raw_json\game_franchises\game\51473.json
raw_json\game_franchises\game\51474.json
raw_json\game_franchises\game\51475.json
raw_json\game_franchises\game\5148.json
raw_json\game_franchises\game\51483.json
raw_json\game_franchises\game\51488.json
raw_json\game_franchises\game\5149.json
raw_json\game_franchises\game\51492.json
raw_json\game_franchises\game\51493.json
raw_json\game_franchises\game\51494.json
raw_json\game_franchises\game\51495.json
raw_json\game_franchises\game\51497.json
raw_json\game_franchises\game\51498.json
raw_json\game_franc

raw_json\game_franchises\game\51955.json
raw_json\game_franchises\game\51956.json
raw_json\game_franchises\game\51957.json
raw_json\game_franchises\game\51958.json
raw_json\game_franchises\game\51959.json
raw_json\game_franchises\game\51960.json
raw_json\game_franchises\game\51961.json
raw_json\game_franchises\game\51962.json
raw_json\game_franchises\game\51963.json
raw_json\game_franchises\game\51964.json
raw_json\game_franchises\game\5197.json
raw_json\game_franchises\game\51972.json
raw_json\game_franchises\game\51974.json
raw_json\game_franchises\game\51977.json
raw_json\game_franchises\game\51983.json
raw_json\game_franchises\game\51989.json
raw_json\game_franchises\game\5199.json
raw_json\game_franchises\game\51990.json
raw_json\game_franchises\game\51991.json
raw_json\game_franchises\game\51995.json
raw_json\game_franchises\game\51998.json
raw_json\game_franchises\game\52.json
raw_json\game_franchises\game\52007.json
raw_json\game_franchises\game\52015.json
raw_json\game_franchi

raw_json\game_franchises\game\52562.json
raw_json\game_franchises\game\5257.json
raw_json\game_franchises\game\52573.json
raw_json\game_franchises\game\52575.json
raw_json\game_franchises\game\52579.json
raw_json\game_franchises\game\52580.json
raw_json\game_franchises\game\52581.json
raw_json\game_franchises\game\52585.json
raw_json\game_franchises\game\5259.json
raw_json\game_franchises\game\52592.json
raw_json\game_franchises\game\52599.json
raw_json\game_franchises\game\52603.json
raw_json\game_franchises\game\52606.json
raw_json\game_franchises\game\52608.json
raw_json\game_franchises\game\52609.json
raw_json\game_franchises\game\5261.json
raw_json\game_franchises\game\5262.json
raw_json\game_franchises\game\52633.json
raw_json\game_franchises\game\5264.json
raw_json\game_franchises\game\52644.json
raw_json\game_franchises\game\52647.json
raw_json\game_franchises\game\5266.json
raw_json\game_franchises\game\52668.json
raw_json\game_franchises\game\52675.json
raw_json\game_franchis

raw_json\game_franchises\game\5336.json
raw_json\game_franchises\game\53363.json
raw_json\game_franchises\game\5337.json
raw_json\game_franchises\game\53374.json
raw_json\game_franchises\game\53376.json
raw_json\game_franchises\game\53380.json
raw_json\game_franchises\game\53381.json
raw_json\game_franchises\game\53384.json
raw_json\game_franchises\game\53385.json
raw_json\game_franchises\game\53386.json
raw_json\game_franchises\game\53392.json
raw_json\game_franchises\game\53394.json
raw_json\game_franchises\game\53395.json
raw_json\game_franchises\game\534.json
raw_json\game_franchises\game\53400.json
raw_json\game_franchises\game\53403.json
raw_json\game_franchises\game\53404.json
raw_json\game_franchises\game\53405.json
raw_json\game_franchises\game\53407.json
raw_json\game_franchises\game\53410.json
raw_json\game_franchises\game\53415.json
raw_json\game_franchises\game\53416.json
raw_json\game_franchises\game\53425.json
raw_json\game_franchises\game\53429.json
raw_json\game_franch

raw_json\game_franchises\game\5403.json
raw_json\game_franchises\game\54030.json
raw_json\game_franchises\game\54032.json
raw_json\game_franchises\game\54033.json
raw_json\game_franchises\game\54034.json
raw_json\game_franchises\game\54035.json
raw_json\game_franchises\game\54036.json
raw_json\game_franchises\game\54037.json
raw_json\game_franchises\game\54039.json
raw_json\game_franchises\game\54042.json
raw_json\game_franchises\game\54044.json
raw_json\game_franchises\game\54045.json
raw_json\game_franchises\game\5405.json
raw_json\game_franchises\game\54053.json
raw_json\game_franchises\game\54056.json
raw_json\game_franchises\game\54058.json
raw_json\game_franchises\game\54059.json
raw_json\game_franchises\game\5406.json
raw_json\game_franchises\game\54062.json
raw_json\game_franchises\game\54066.json
raw_json\game_franchises\game\54069.json
raw_json\game_franchises\game\54071.json
raw_json\game_franchises\game\54074.json
raw_json\game_franchises\game\54081.json
raw_json\game_franc

raw_json\game_franchises\game\54679.json
raw_json\game_franchises\game\54680.json
raw_json\game_franchises\game\54682.json
raw_json\game_franchises\game\54684.json
raw_json\game_franchises\game\54685.json
raw_json\game_franchises\game\54687.json
raw_json\game_franchises\game\54689.json
raw_json\game_franchises\game\5469.json
raw_json\game_franchises\game\54702.json
raw_json\game_franchises\game\54703.json
raw_json\game_franchises\game\5471.json
raw_json\game_franchises\game\54719.json
raw_json\game_franchises\game\54729.json
raw_json\game_franchises\game\54733.json
raw_json\game_franchises\game\54734.json
raw_json\game_franchises\game\54735.json
raw_json\game_franchises\game\54739.json
raw_json\game_franchises\game\54750.json
raw_json\game_franchises\game\54761.json
raw_json\game_franchises\game\54762.json
raw_json\game_franchises\game\54763.json
raw_json\game_franchises\game\54769.json
raw_json\game_franchises\game\5477.json
raw_json\game_franchises\game\5478.json
raw_json\game_franch

raw_json\game_franchises\game\55419.json
raw_json\game_franchises\game\5542.json
raw_json\game_franchises\game\55427.json
raw_json\game_franchises\game\55434.json
raw_json\game_franchises\game\55435.json
raw_json\game_franchises\game\55437.json
raw_json\game_franchises\game\55444.json
raw_json\game_franchises\game\55445.json
raw_json\game_franchises\game\55446.json
raw_json\game_franchises\game\55447.json
raw_json\game_franchises\game\55448.json
raw_json\game_franchises\game\55449.json
raw_json\game_franchises\game\55454.json
raw_json\game_franchises\game\55459.json
raw_json\game_franchises\game\5546.json
raw_json\game_franchises\game\55468.json
raw_json\game_franchises\game\55469.json
raw_json\game_franchises\game\55470.json
raw_json\game_franchises\game\55472.json
raw_json\game_franchises\game\55473.json
raw_json\game_franchises\game\55474.json
raw_json\game_franchises\game\55477.json
raw_json\game_franchises\game\55481.json
raw_json\game_franchises\game\5550.json
raw_json\game_franc

raw_json\game_franchises\game\56743.json
raw_json\game_franchises\game\56744.json
raw_json\game_franchises\game\56746.json
raw_json\game_franchises\game\5676.json
raw_json\game_franchises\game\5677.json
raw_json\game_franchises\game\56772.json
raw_json\game_franchises\game\56774.json
raw_json\game_franchises\game\56783.json
raw_json\game_franchises\game\56786.json
raw_json\game_franchises\game\56787.json
raw_json\game_franchises\game\5679.json
raw_json\game_franchises\game\56798.json
raw_json\game_franchises\game\5680.json
raw_json\game_franchises\game\5681.json
raw_json\game_franchises\game\56817.json
raw_json\game_franchises\game\5682.json
raw_json\game_franchises\game\56824.json
raw_json\game_franchises\game\56834.json
raw_json\game_franchises\game\56835.json
raw_json\game_franchises\game\56836.json
raw_json\game_franchises\game\56837.json
raw_json\game_franchises\game\5684.json
raw_json\game_franchises\game\56841.json
raw_json\game_franchises\game\56852.json
raw_json\game_franchise

raw_json\game_franchises\game\57633.json
raw_json\game_franchises\game\57634.json
raw_json\game_franchises\game\57635.json
raw_json\game_franchises\game\57636.json
raw_json\game_franchises\game\57637.json
raw_json\game_franchises\game\57638.json
raw_json\game_franchises\game\57639.json
raw_json\game_franchises\game\5764.json
raw_json\game_franchises\game\57640.json
raw_json\game_franchises\game\57646.json
raw_json\game_franchises\game\57651.json
raw_json\game_franchises\game\57658.json
raw_json\game_franchises\game\57669.json
raw_json\game_franchises\game\5767.json
raw_json\game_franchises\game\57675.json
raw_json\game_franchises\game\57676.json
raw_json\game_franchises\game\57677.json
raw_json\game_franchises\game\5768.json
raw_json\game_franchises\game\57687.json
raw_json\game_franchises\game\57688.json
raw_json\game_franchises\game\57689.json
raw_json\game_franchises\game\5769.json
raw_json\game_franchises\game\57690.json
raw_json\game_franchises\game\57691.json
raw_json\game_franch

raw_json\game_franchises\game\5820.json
raw_json\game_franchises\game\58200.json
raw_json\game_franchises\game\5821.json
raw_json\game_franchises\game\58211.json
raw_json\game_franchises\game\5822.json
raw_json\game_franchises\game\58235.json
raw_json\game_franchises\game\58236.json
raw_json\game_franchises\game\58237.json
raw_json\game_franchises\game\58238.json
raw_json\game_franchises\game\58239.json
raw_json\game_franchises\game\58242.json
raw_json\game_franchises\game\58247.json
raw_json\game_franchises\game\5825.json
raw_json\game_franchises\game\58251.json
raw_json\game_franchises\game\58252.json
raw_json\game_franchises\game\58257.json
raw_json\game_franchises\game\58260.json
raw_json\game_franchises\game\58262.json
raw_json\game_franchises\game\58263.json
raw_json\game_franchises\game\58264.json
raw_json\game_franchises\game\58265.json
raw_json\game_franchises\game\58266.json
raw_json\game_franchises\game\58267.json
raw_json\game_franchises\game\58268.json
raw_json\game_franch

raw_json\game_franchises\game\58810.json
raw_json\game_franchises\game\58815.json
raw_json\game_franchises\game\58843.json
raw_json\game_franchises\game\58844.json
raw_json\game_franchises\game\58845.json
raw_json\game_franchises\game\58847.json
raw_json\game_franchises\game\5885.json
raw_json\game_franchises\game\58867.json
raw_json\game_franchises\game\58869.json
raw_json\game_franchises\game\5887.json
raw_json\game_franchises\game\58874.json
raw_json\game_franchises\game\58878.json
raw_json\game_franchises\game\58879.json
raw_json\game_franchises\game\58880.json
raw_json\game_franchises\game\58881.json
raw_json\game_franchises\game\58882.json
raw_json\game_franchises\game\58883.json
raw_json\game_franchises\game\58884.json
raw_json\game_franchises\game\58885.json
raw_json\game_franchises\game\58886.json
raw_json\game_franchises\game\58887.json
raw_json\game_franchises\game\58893.json
raw_json\game_franchises\game\58902.json
raw_json\game_franchises\game\58907.json
raw_json\game_fran

raw_json\game_franchises\game\59557.json
raw_json\game_franchises\game\59568.json
raw_json\game_franchises\game\5957.json
raw_json\game_franchises\game\59593.json
raw_json\game_franchises\game\59596.json
raw_json\game_franchises\game\596.json
raw_json\game_franchises\game\5960.json
raw_json\game_franchises\game\59609.json
raw_json\game_franchises\game\5961.json
raw_json\game_franchises\game\59611.json
raw_json\game_franchises\game\59617.json
raw_json\game_franchises\game\5962.json
raw_json\game_franchises\game\59626.json
raw_json\game_franchises\game\59629.json
raw_json\game_franchises\game\59637.json
raw_json\game_franchises\game\59638.json
raw_json\game_franchises\game\5964.json
raw_json\game_franchises\game\59641.json
raw_json\game_franchises\game\59643.json
raw_json\game_franchises\game\5965.json
raw_json\game_franchises\game\59658.json
raw_json\game_franchises\game\59659.json
raw_json\game_franchises\game\5966.json
raw_json\game_franchises\game\59666.json
raw_json\game_franchises\

raw_json\game_franchises\game\60165.json
raw_json\game_franchises\game\6017.json
raw_json\game_franchises\game\60170.json
raw_json\game_franchises\game\60172.json
raw_json\game_franchises\game\60173.json
raw_json\game_franchises\game\60175.json
raw_json\game_franchises\game\60181.json
raw_json\game_franchises\game\60203.json
raw_json\game_franchises\game\6021.json
raw_json\game_franchises\game\60211.json
raw_json\game_franchises\game\60212.json
raw_json\game_franchises\game\60216.json
raw_json\game_franchises\game\60224.json
raw_json\game_franchises\game\60226.json
raw_json\game_franchises\game\60227.json
raw_json\game_franchises\game\60229.json
raw_json\game_franchises\game\60238.json
raw_json\game_franchises\game\60241.json
raw_json\game_franchises\game\60244.json
raw_json\game_franchises\game\60245.json
raw_json\game_franchises\game\60246.json
raw_json\game_franchises\game\60247.json
raw_json\game_franchises\game\60250.json
raw_json\game_franchises\game\60251.json
raw_json\game_fran

raw_json\game_franchises\game\60942.json
raw_json\game_franchises\game\60946.json
raw_json\game_franchises\game\60947.json
raw_json\game_franchises\game\60953.json
raw_json\game_franchises\game\60957.json
raw_json\game_franchises\game\60958.json
raw_json\game_franchises\game\6096.json
raw_json\game_franchises\game\60964.json
raw_json\game_franchises\game\60967.json
raw_json\game_franchises\game\60968.json
raw_json\game_franchises\game\60969.json
raw_json\game_franchises\game\6097.json
raw_json\game_franchises\game\60970.json
raw_json\game_franchises\game\60977.json
raw_json\game_franchises\game\60979.json
raw_json\game_franchises\game\60980.json
raw_json\game_franchises\game\60981.json
raw_json\game_franchises\game\60984.json
raw_json\game_franchises\game\60986.json
raw_json\game_franchises\game\60987.json
raw_json\game_franchises\game\60988.json
raw_json\game_franchises\game\60989.json
raw_json\game_franchises\game\60990.json
raw_json\game_franchises\game\60991.json
raw_json\game_fran

raw_json\game_franchises\game\6140.json
raw_json\game_franchises\game\61408.json
raw_json\game_franchises\game\6141.json
raw_json\game_franchises\game\61419.json
raw_json\game_franchises\game\61421.json
raw_json\game_franchises\game\61422.json
raw_json\game_franchises\game\61424.json
raw_json\game_franchises\game\61429.json
raw_json\game_franchises\game\6143.json
raw_json\game_franchises\game\61430.json
raw_json\game_franchises\game\61448.json
raw_json\game_franchises\game\6145.json
raw_json\game_franchises\game\61451.json
raw_json\game_franchises\game\61452.json
raw_json\game_franchises\game\61456.json
raw_json\game_franchises\game\61457.json
raw_json\game_franchises\game\61458.json
raw_json\game_franchises\game\61459.json
raw_json\game_franchises\game\61461.json
raw_json\game_franchises\game\61462.json
raw_json\game_franchises\game\61463.json
raw_json\game_franchises\game\6147.json
raw_json\game_franchises\game\61472.json
raw_json\game_franchises\game\61476.json
raw_json\game_franchi

raw_json\game_franchises\game\62264.json
raw_json\game_franchises\game\62265.json
raw_json\game_franchises\game\62266.json
raw_json\game_franchises\game\62267.json
raw_json\game_franchises\game\62270.json
raw_json\game_franchises\game\62281.json
raw_json\game_franchises\game\62283.json
raw_json\game_franchises\game\62285.json
raw_json\game_franchises\game\62287.json
raw_json\game_franchises\game\62296.json
raw_json\game_franchises\game\62297.json
raw_json\game_franchises\game\62298.json
raw_json\game_franchises\game\62299.json
raw_json\game_franchises\game\623.json
raw_json\game_franchises\game\62300.json
raw_json\game_franchises\game\62301.json
raw_json\game_franchises\game\62302.json
raw_json\game_franchises\game\62303.json
raw_json\game_franchises\game\62304.json
raw_json\game_franchises\game\62305.json
raw_json\game_franchises\game\62308.json
raw_json\game_franchises\game\6231.json
raw_json\game_franchises\game\6232.json
raw_json\game_franchises\game\62328.json
raw_json\game_franch

raw_json\game_franchises\game\6304.json
raw_json\game_franchises\game\63043.json
raw_json\game_franchises\game\63048.json
raw_json\game_franchises\game\63051.json
raw_json\game_franchises\game\63058.json
raw_json\game_franchises\game\63061.json
raw_json\game_franchises\game\63062.json
raw_json\game_franchises\game\63063.json
raw_json\game_franchises\game\63069.json
raw_json\game_franchises\game\63073.json
raw_json\game_franchises\game\63075.json
raw_json\game_franchises\game\6308.json
raw_json\game_franchises\game\63089.json
raw_json\game_franchises\game\6309.json
raw_json\game_franchises\game\63090.json
raw_json\game_franchises\game\63101.json
raw_json\game_franchises\game\63107.json
raw_json\game_franchises\game\6311.json
raw_json\game_franchises\game\63110.json
raw_json\game_franchises\game\63111.json
raw_json\game_franchises\game\63113.json
raw_json\game_franchises\game\63117.json
raw_json\game_franchises\game\63119.json
raw_json\game_franchises\game\63123.json
raw_json\game_franch

raw_json\game_franchises\game\64276.json
raw_json\game_franchises\game\64277.json
raw_json\game_franchises\game\64278.json
raw_json\game_franchises\game\64279.json
raw_json\game_franchises\game\64280.json
raw_json\game_franchises\game\64281.json
raw_json\game_franchises\game\64282.json
raw_json\game_franchises\game\64283.json
raw_json\game_franchises\game\6429.json
raw_json\game_franchises\game\64298.json
raw_json\game_franchises\game\6430.json
raw_json\game_franchises\game\64301.json
raw_json\game_franchises\game\64320.json
raw_json\game_franchises\game\64335.json
raw_json\game_franchises\game\64344.json
raw_json\game_franchises\game\64345.json
raw_json\game_franchises\game\64355.json
raw_json\game_franchises\game\64357.json
raw_json\game_franchises\game\64358.json
raw_json\game_franchises\game\64359.json
raw_json\game_franchises\game\64360.json
raw_json\game_franchises\game\64361.json
raw_json\game_franchises\game\64362.json
raw_json\game_franchises\game\6437.json
raw_json\game_franc

raw_json\game_franchises\game\64927.json
raw_json\game_franchises\game\64928.json
raw_json\game_franchises\game\64929.json
raw_json\game_franchises\game\64930.json
raw_json\game_franchises\game\64931.json
raw_json\game_franchises\game\64932.json
raw_json\game_franchises\game\64933.json
raw_json\game_franchises\game\64934.json
raw_json\game_franchises\game\64935.json
raw_json\game_franchises\game\64936.json
raw_json\game_franchises\game\64937.json
raw_json\game_franchises\game\64938.json
raw_json\game_franchises\game\6495.json
raw_json\game_franchises\game\64951.json
raw_json\game_franchises\game\6496.json
raw_json\game_franchises\game\64977.json
raw_json\game_franchises\game\6499.json
raw_json\game_franchises\game\65.json
raw_json\game_franchises\game\650.json
raw_json\game_franchises\game\65014.json
raw_json\game_franchises\game\6503.json
raw_json\game_franchises\game\65041.json
raw_json\game_franchises\game\65043.json
raw_json\game_franchises\game\6505.json
raw_json\game_franchises\g

raw_json\game_franchises\game\65932.json
raw_json\game_franchises\game\65959.json
raw_json\game_franchises\game\6596.json
raw_json\game_franchises\game\65960.json
raw_json\game_franchises\game\65961.json
raw_json\game_franchises\game\65962.json
raw_json\game_franchises\game\65966.json
raw_json\game_franchises\game\6597.json
raw_json\game_franchises\game\65972.json
raw_json\game_franchises\game\65986.json
raw_json\game_franchises\game\66.json
raw_json\game_franchises\game\66000.json
raw_json\game_franchises\game\66001.json
raw_json\game_franchises\game\66002.json
raw_json\game_franchises\game\66003.json
raw_json\game_franchises\game\66004.json
raw_json\game_franchises\game\66005.json
raw_json\game_franchises\game\6601.json
raw_json\game_franchises\game\6602.json
raw_json\game_franchises\game\66026.json
raw_json\game_franchises\game\6603.json
raw_json\game_franchises\game\66032.json
raw_json\game_franchises\game\66033.json
raw_json\game_franchises\game\66034.json
raw_json\game_franchises

raw_json\game_franchises\game\66697.json
raw_json\game_franchises\game\6671.json
raw_json\game_franchises\game\66712.json
raw_json\game_franchises\game\66719.json
raw_json\game_franchises\game\66725.json
raw_json\game_franchises\game\66728.json
raw_json\game_franchises\game\6673.json
raw_json\game_franchises\game\66747.json
raw_json\game_franchises\game\6675.json
raw_json\game_franchises\game\66771.json
raw_json\game_franchises\game\66784.json
raw_json\game_franchises\game\6679.json
raw_json\game_franchises\game\66807.json
raw_json\game_franchises\game\6681.json
raw_json\game_franchises\game\66818.json
raw_json\game_franchises\game\66826.json
raw_json\game_franchises\game\6683.json
raw_json\game_franchises\game\66834.json
raw_json\game_franchises\game\66842.json
raw_json\game_franchises\game\6687.json
raw_json\game_franchises\game\66872.json
raw_json\game_franchises\game\66873.json
raw_json\game_franchises\game\66874.json
raw_json\game_franchises\game\66879.json
raw_json\game_franchise

raw_json\game_franchises\game\67437.json
raw_json\game_franchises\game\67438.json
raw_json\game_franchises\game\67439.json
raw_json\game_franchises\game\6744.json
raw_json\game_franchises\game\67440.json
raw_json\game_franchises\game\67441.json
raw_json\game_franchises\game\67442.json
raw_json\game_franchises\game\67443.json
raw_json\game_franchises\game\67449.json
raw_json\game_franchises\game\67451.json
raw_json\game_franchises\game\67457.json
raw_json\game_franchises\game\67487.json
raw_json\game_franchises\game\6749.json
raw_json\game_franchises\game\67490.json
raw_json\game_franchises\game\67492.json
raw_json\game_franchises\game\67501.json
raw_json\game_franchises\game\67513.json
raw_json\game_franchises\game\67524.json
raw_json\game_franchises\game\67525.json
raw_json\game_franchises\game\6753.json
raw_json\game_franchises\game\67537.json
raw_json\game_franchises\game\67538.json
raw_json\game_franchises\game\67539.json
raw_json\game_franchises\game\6754.json
raw_json\game_franch

raw_json\game_franchises\game\68200.json
raw_json\game_franchises\game\68201.json
raw_json\game_franchises\game\6822.json
raw_json\game_franchises\game\6824.json
raw_json\game_franchises\game\68263.json
raw_json\game_franchises\game\68266.json
raw_json\game_franchises\game\68268.json
raw_json\game_franchises\game\68272.json
raw_json\game_franchises\game\68273.json
raw_json\game_franchises\game\68274.json
raw_json\game_franchises\game\6828.json
raw_json\game_franchises\game\68282.json
raw_json\game_franchises\game\68284.json
raw_json\game_franchises\game\6829.json
raw_json\game_franchises\game\68292.json
raw_json\game_franchises\game\6830.json
raw_json\game_franchises\game\68304.json
raw_json\game_franchises\game\68305.json
raw_json\game_franchises\game\6833.json
raw_json\game_franchises\game\68335.json
raw_json\game_franchises\game\6834.json
raw_json\game_franchises\game\6836.json
raw_json\game_franchises\game\68372.json
raw_json\game_franchises\game\68373.json
raw_json\game_franchises

raw_json\game_franchises\game\69124.json
raw_json\game_franchises\game\6913.json
raw_json\game_franchises\game\69140.json
raw_json\game_franchises\game\69143.json
raw_json\game_franchises\game\69146.json
raw_json\game_franchises\game\69162.json
raw_json\game_franchises\game\69165.json
raw_json\game_franchises\game\69171.json
raw_json\game_franchises\game\69174.json
raw_json\game_franchises\game\69179.json
raw_json\game_franchises\game\6919.json
raw_json\game_franchises\game\69193.json
raw_json\game_franchises\game\69194.json
raw_json\game_franchises\game\692.json
raw_json\game_franchises\game\6920.json
raw_json\game_franchises\game\69202.json
raw_json\game_franchises\game\69206.json
raw_json\game_franchises\game\6921.json
raw_json\game_franchises\game\6922.json
raw_json\game_franchises\game\69220.json
raw_json\game_franchises\game\69222.json
raw_json\game_franchises\game\69223.json
raw_json\game_franchises\game\69228.json
raw_json\game_franchises\game\6923.json
raw_json\game_franchises

raw_json\game_franchises\game\70082.json
raw_json\game_franchises\game\70089.json
raw_json\game_franchises\game\7009.json
raw_json\game_franchises\game\70103.json
raw_json\game_franchises\game\70104.json
raw_json\game_franchises\game\70107.json
raw_json\game_franchises\game\70118.json
raw_json\game_franchises\game\7012.json
raw_json\game_franchises\game\70122.json
raw_json\game_franchises\game\70128.json
raw_json\game_franchises\game\7013.json
raw_json\game_franchises\game\70134.json
raw_json\game_franchises\game\70135.json
raw_json\game_franchises\game\70145.json
raw_json\game_franchises\game\7015.json
raw_json\game_franchises\game\70152.json
raw_json\game_franchises\game\70153.json
raw_json\game_franchises\game\70154.json
raw_json\game_franchises\game\70155.json
raw_json\game_franchises\game\70156.json
raw_json\game_franchises\game\70157.json
raw_json\game_franchises\game\70158.json
raw_json\game_franchises\game\70159.json
raw_json\game_franchises\game\70160.json
raw_json\game_franch

raw_json\game_franchises\game\70950.json
raw_json\game_franchises\game\70955.json
raw_json\game_franchises\game\70956.json
raw_json\game_franchises\game\70957.json
raw_json\game_franchises\game\70958.json
raw_json\game_franchises\game\7096.json
raw_json\game_franchises\game\70961.json
raw_json\game_franchises\game\70962.json
raw_json\game_franchises\game\70963.json
raw_json\game_franchises\game\70964.json
raw_json\game_franchises\game\70965.json
raw_json\game_franchises\game\7097.json
raw_json\game_franchises\game\70980.json
raw_json\game_franchises\game\70981.json
raw_json\game_franchises\game\70982.json
raw_json\game_franchises\game\70983.json
raw_json\game_franchises\game\70984.json
raw_json\game_franchises\game\70985.json
raw_json\game_franchises\game\70986.json
raw_json\game_franchises\game\70987.json
raw_json\game_franchises\game\70988.json
raw_json\game_franchises\game\7099.json
raw_json\game_franchises\game\70993.json
raw_json\game_franchises\game\70998.json
raw_json\game_franc

raw_json\game_franchises\game\7190.json
raw_json\game_franchises\game\71900.json
raw_json\game_franchises\game\71913.json
raw_json\game_franchises\game\71915.json
raw_json\game_franchises\game\71916.json
raw_json\game_franchises\game\7192.json
raw_json\game_franchises\game\71920.json
raw_json\game_franchises\game\71937.json
raw_json\game_franchises\game\71942.json
raw_json\game_franchises\game\71957.json
raw_json\game_franchises\game\71958.json
raw_json\game_franchises\game\71960.json
raw_json\game_franchises\game\71968.json
raw_json\game_franchises\game\7197.json
raw_json\game_franchises\game\71974.json
raw_json\game_franchises\game\7198.json
raw_json\game_franchises\game\71998.json
raw_json\game_franchises\game\72.json
raw_json\game_franchises\game\720.json
raw_json\game_franchises\game\7201.json
raw_json\game_franchises\game\72014.json
raw_json\game_franchises\game\7202.json
raw_json\game_franchises\game\7204.json
raw_json\game_franchises\game\72043.json
raw_json\game_franchises\gam

raw_json\game_franchises\game\7294.json
raw_json\game_franchises\game\72941.json
raw_json\game_franchises\game\72943.json
raw_json\game_franchises\game\72947.json
raw_json\game_franchises\game\72948.json
raw_json\game_franchises\game\72951.json
raw_json\game_franchises\game\7296.json
raw_json\game_franchises\game\7297.json
raw_json\game_franchises\game\72972.json
raw_json\game_franchises\game\72973.json
raw_json\game_franchises\game\72974.json
raw_json\game_franchises\game\72975.json
raw_json\game_franchises\game\72976.json
raw_json\game_franchises\game\7298.json
raw_json\game_franchises\game\72982.json
raw_json\game_franchises\game\72984.json
raw_json\game_franchises\game\72985.json
raw_json\game_franchises\game\72986.json
raw_json\game_franchises\game\72987.json
raw_json\game_franchises\game\73.json
raw_json\game_franchises\game\730.json
raw_json\game_franchises\game\7300.json
raw_json\game_franchises\game\73003.json
raw_json\game_franchises\game\73007.json
raw_json\game_franchises\g

raw_json\game_franchises\game\7360.json
raw_json\game_franchises\game\73601.json
raw_json\game_franchises\game\73604.json
raw_json\game_franchises\game\73607.json
raw_json\game_franchises\game\73608.json
raw_json\game_franchises\game\73609.json
raw_json\game_franchises\game\7361.json
raw_json\game_franchises\game\73610.json
raw_json\game_franchises\game\73611.json
raw_json\game_franchises\game\73612.json
raw_json\game_franchises\game\73613.json
raw_json\game_franchises\game\73614.json
raw_json\game_franchises\game\73615.json
raw_json\game_franchises\game\7362.json
raw_json\game_franchises\game\73629.json
raw_json\game_franchises\game\7363.json
raw_json\game_franchises\game\73632.json
raw_json\game_franchises\game\73633.json
raw_json\game_franchises\game\73635.json
raw_json\game_franchises\game\73636.json
raw_json\game_franchises\game\73638.json
raw_json\game_franchises\game\7364.json
raw_json\game_franchises\game\73640.json
raw_json\game_franchises\game\73641.json
raw_json\game_franchi

raw_json\game_franchises\game\74335.json
raw_json\game_franchises\game\74336.json
raw_json\game_franchises\game\74337.json
raw_json\game_franchises\game\7434.json
raw_json\game_franchises\game\74347.json
raw_json\game_franchises\game\74348.json
raw_json\game_franchises\game\74349.json
raw_json\game_franchises\game\74350.json
raw_json\game_franchises\game\74354.json
raw_json\game_franchises\game\7436.json
raw_json\game_franchises\game\7437.json
raw_json\game_franchises\game\74378.json
raw_json\game_franchises\game\7438.json
raw_json\game_franchises\game\74394.json
raw_json\game_franchises\game\744.json
raw_json\game_franchises\game\7440.json
raw_json\game_franchises\game\7442.json
raw_json\game_franchises\game\74423.json
raw_json\game_franchises\game\74424.json
raw_json\game_franchises\game\74432.json
raw_json\game_franchises\game\74447.json
raw_json\game_franchises\game\74448.json
raw_json\game_franchises\game\74449.json
raw_json\game_franchises\game\7445.json
raw_json\game_franchises\

raw_json\game_franchises\game\75084.json
raw_json\game_franchises\game\75087.json
raw_json\game_franchises\game\75095.json
raw_json\game_franchises\game\751.json
raw_json\game_franchises\game\7510.json
raw_json\game_franchises\game\75116.json
raw_json\game_franchises\game\75128.json
raw_json\game_franchises\game\7513.json
raw_json\game_franchises\game\75135.json
raw_json\game_franchises\game\75136.json
raw_json\game_franchises\game\75137.json
raw_json\game_franchises\game\75153.json
raw_json\game_franchises\game\75154.json
raw_json\game_franchises\game\75164.json
raw_json\game_franchises\game\75166.json
raw_json\game_franchises\game\75167.json
raw_json\game_franchises\game\75168.json
raw_json\game_franchises\game\75169.json
raw_json\game_franchises\game\75170.json
raw_json\game_franchises\game\75172.json
raw_json\game_franchises\game\75174.json
raw_json\game_franchises\game\75175.json
raw_json\game_franchises\game\75176.json
raw_json\game_franchises\game\75178.json
raw_json\game_franch

raw_json\game_franchises\game\75886.json
raw_json\game_franchises\game\7589.json
raw_json\game_franchises\game\75890.json
raw_json\game_franchises\game\75892.json
raw_json\game_franchises\game\75897.json
raw_json\game_franchises\game\759.json
raw_json\game_franchises\game\7590.json
raw_json\game_franchises\game\7591.json
raw_json\game_franchises\game\75912.json
raw_json\game_franchises\game\75914.json
raw_json\game_franchises\game\75915.json
raw_json\game_franchises\game\75924.json
raw_json\game_franchises\game\75929.json
raw_json\game_franchises\game\7593.json
raw_json\game_franchises\game\75930.json
raw_json\game_franchises\game\75948.json
raw_json\game_franchises\game\75950.json
raw_json\game_franchises\game\75951.json
raw_json\game_franchises\game\75953.json
raw_json\game_franchises\game\75956.json
raw_json\game_franchises\game\75963.json
raw_json\game_franchises\game\7597.json
raw_json\game_franchises\game\75976.json
raw_json\game_franchises\game\7598.json
raw_json\game_franchises

raw_json\game_franchises\game\76825.json
raw_json\game_franchises\game\76834.json
raw_json\game_franchises\game\76850.json
raw_json\game_franchises\game\76851.json
raw_json\game_franchises\game\76852.json
raw_json\game_franchises\game\76858.json
raw_json\game_franchises\game\76859.json
raw_json\game_franchises\game\76863.json
raw_json\game_franchises\game\76864.json
raw_json\game_franchises\game\76869.json
raw_json\game_franchises\game\7687.json
raw_json\game_franchises\game\76873.json
raw_json\game_franchises\game\7688.json
raw_json\game_franchises\game\76880.json
raw_json\game_franchises\game\76885.json
raw_json\game_franchises\game\76886.json
raw_json\game_franchises\game\7689.json
raw_json\game_franchises\game\76890.json
raw_json\game_franchises\game\76891.json
raw_json\game_franchises\game\76892.json
raw_json\game_franchises\game\76893.json
raw_json\game_franchises\game\76894.json
raw_json\game_franchises\game\76895.json
raw_json\game_franchises\game\76896.json
raw_json\game_franc

raw_json\game_franchises\game\77623.json
raw_json\game_franchises\game\77624.json
raw_json\game_franchises\game\77657.json
raw_json\game_franchises\game\77658.json
raw_json\game_franchises\game\7766.json
raw_json\game_franchises\game\77660.json
raw_json\game_franchises\game\77667.json
raw_json\game_franchises\game\77675.json
raw_json\game_franchises\game\77676.json
raw_json\game_franchises\game\77677.json
raw_json\game_franchises\game\77678.json
raw_json\game_franchises\game\77686.json
raw_json\game_franchises\game\7769.json
raw_json\game_franchises\game\77691.json
raw_json\game_franchises\game\77695.json
raw_json\game_franchises\game\7770.json
raw_json\game_franchises\game\77721.json
raw_json\game_franchises\game\77733.json
raw_json\game_franchises\game\77734.json
raw_json\game_franchises\game\7774.json
raw_json\game_franchises\game\77744.json
raw_json\game_franchises\game\77745.json
raw_json\game_franchises\game\77749.json
raw_json\game_franchises\game\77752.json
raw_json\game_franch

raw_json\game_franchises\game\78651.json
raw_json\game_franchises\game\78652.json
raw_json\game_franchises\game\7866.json
raw_json\game_franchises\game\78674.json
raw_json\game_franchises\game\78676.json
raw_json\game_franchises\game\78677.json
raw_json\game_franchises\game\78678.json
raw_json\game_franchises\game\7868.json
raw_json\game_franchises\game\78695.json
raw_json\game_franchises\game\787.json
raw_json\game_franchises\game\78715.json
raw_json\game_franchises\game\78716.json
raw_json\game_franchises\game\78724.json
raw_json\game_franchises\game\78725.json
raw_json\game_franchises\game\78727.json
raw_json\game_franchises\game\78728.json
raw_json\game_franchises\game\78731.json
raw_json\game_franchises\game\78734.json
raw_json\game_franchises\game\7874.json
raw_json\game_franchises\game\78749.json
raw_json\game_franchises\game\7875.json
raw_json\game_franchises\game\78761.json
raw_json\game_franchises\game\78762.json
raw_json\game_franchises\game\78763.json
raw_json\game_franchis

raw_json\game_franchises\game\79683.json
raw_json\game_franchises\game\79686.json
raw_json\game_franchises\game\79687.json
raw_json\game_franchises\game\79688.json
raw_json\game_franchises\game\79689.json
raw_json\game_franchises\game\79690.json
raw_json\game_franchises\game\79693.json
raw_json\game_franchises\game\79695.json
raw_json\game_franchises\game\79696.json
raw_json\game_franchises\game\79697.json
raw_json\game_franchises\game\797.json
raw_json\game_franchises\game\79711.json
raw_json\game_franchises\game\7972.json
raw_json\game_franchises\game\79722.json
raw_json\game_franchises\game\79723.json
raw_json\game_franchises\game\79724.json
raw_json\game_franchises\game\79725.json
raw_json\game_franchises\game\79726.json
raw_json\game_franchises\game\79727.json
raw_json\game_franchises\game\79728.json
raw_json\game_franchises\game\79729.json
raw_json\game_franchises\game\79730.json
raw_json\game_franchises\game\79731.json
raw_json\game_franchises\game\79732.json
raw_json\game_franc

raw_json\game_franchises\game\80559.json
raw_json\game_franchises\game\8056.json
raw_json\game_franchises\game\80569.json
raw_json\game_franchises\game\8057.json
raw_json\game_franchises\game\80571.json
raw_json\game_franchises\game\80572.json
raw_json\game_franchises\game\80573.json
raw_json\game_franchises\game\80580.json
raw_json\game_franchises\game\80585.json
raw_json\game_franchises\game\80590.json
raw_json\game_franchises\game\80596.json
raw_json\game_franchises\game\806.json
raw_json\game_franchises\game\80615.json
raw_json\game_franchises\game\80622.json
raw_json\game_franchises\game\80623.json
raw_json\game_franchises\game\8063.json
raw_json\game_franchises\game\80638.json
raw_json\game_franchises\game\80639.json
raw_json\game_franchises\game\80640.json
raw_json\game_franchises\game\80641.json
raw_json\game_franchises\game\80642.json
raw_json\game_franchises\game\80643.json
raw_json\game_franchises\game\80644.json
raw_json\game_franchises\game\80645.json
raw_json\game_franchi

raw_json\game_franchises\game\8139.json
raw_json\game_franchises\game\81390.json
raw_json\game_franchises\game\81396.json
raw_json\game_franchises\game\81397.json
raw_json\game_franchises\game\814.json
raw_json\game_franchises\game\8141.json
raw_json\game_franchises\game\8142.json
raw_json\game_franchises\game\81427.json
raw_json\game_franchises\game\81428.json
raw_json\game_franchises\game\8143.json
raw_json\game_franchises\game\81431.json
raw_json\game_franchises\game\81432.json
raw_json\game_franchises\game\81441.json
raw_json\game_franchises\game\81442.json
raw_json\game_franchises\game\81443.json
raw_json\game_franchises\game\81445.json
raw_json\game_franchises\game\8145.json
raw_json\game_franchises\game\81450.json
raw_json\game_franchises\game\81453.json
raw_json\game_franchises\game\81456.json
raw_json\game_franchises\game\81457.json
raw_json\game_franchises\game\8146.json
raw_json\game_franchises\game\8147.json
raw_json\game_franchises\game\81477.json
raw_json\game_franchises\

raw_json\game_franchises\game\82185.json
raw_json\game_franchises\game\82190.json
raw_json\game_franchises\game\82196.json
raw_json\game_franchises\game\82205.json
raw_json\game_franchises\game\8221.json
raw_json\game_franchises\game\82212.json
raw_json\game_franchises\game\82219.json
raw_json\game_franchises\game\82239.json
raw_json\game_franchises\game\8224.json
raw_json\game_franchises\game\82262.json
raw_json\game_franchises\game\82273.json
raw_json\game_franchises\game\82276.json
raw_json\game_franchises\game\82277.json
raw_json\game_franchises\game\8228.json
raw_json\game_franchises\game\823.json
raw_json\game_franchises\game\8231.json
raw_json\game_franchises\game\82312.json
raw_json\game_franchises\game\82313.json
raw_json\game_franchises\game\82323.json
raw_json\game_franchises\game\82324.json
raw_json\game_franchises\game\82327.json
raw_json\game_franchises\game\82328.json
raw_json\game_franchises\game\82329.json
raw_json\game_franchises\game\8233.json
raw_json\game_franchise

raw_json\game_franchises\game\83063.json
raw_json\game_franchises\game\83064.json
raw_json\game_franchises\game\83068.json
raw_json\game_franchises\game\83069.json
raw_json\game_franchises\game\8307.json
raw_json\game_franchises\game\8308.json
raw_json\game_franchises\game\83088.json
raw_json\game_franchises\game\83090.json
raw_json\game_franchises\game\83091.json
raw_json\game_franchises\game\831.json
raw_json\game_franchises\game\83100.json
raw_json\game_franchises\game\83101.json
raw_json\game_franchises\game\83105.json
raw_json\game_franchises\game\83110.json
raw_json\game_franchises\game\83126.json
raw_json\game_franchises\game\83127.json
raw_json\game_franchises\game\83128.json
raw_json\game_franchises\game\83129.json
raw_json\game_franchises\game\83130.json
raw_json\game_franchises\game\83131.json
raw_json\game_franchises\game\83132.json
raw_json\game_franchises\game\8314.json
raw_json\game_franchises\game\83143.json
raw_json\game_franchises\game\83145.json
raw_json\game_franchi

raw_json\game_franchises\game\83826.json
raw_json\game_franchises\game\83827.json
raw_json\game_franchises\game\83828.json
raw_json\game_franchises\game\8383.json
raw_json\game_franchises\game\83833.json
raw_json\game_franchises\game\83844.json
raw_json\game_franchises\game\83845.json
raw_json\game_franchises\game\8385.json
raw_json\game_franchises\game\83859.json
raw_json\game_franchises\game\83862.json
raw_json\game_franchises\game\83863.json
raw_json\game_franchises\game\83864.json
raw_json\game_franchises\game\83865.json
raw_json\game_franchises\game\83867.json
raw_json\game_franchises\game\83876.json
raw_json\game_franchises\game\83879.json
raw_json\game_franchises\game\8388.json
raw_json\game_franchises\game\83880.json
raw_json\game_franchises\game\83881.json
raw_json\game_franchises\game\83882.json
raw_json\game_franchises\game\83883.json
raw_json\game_franchises\game\83885.json
raw_json\game_franchises\game\83886.json
raw_json\game_franchises\game\83898.json
raw_json\game_franc

raw_json\game_franchises\game\8448.json
raw_json\game_franchises\game\84480.json
raw_json\game_franchises\game\84481.json
raw_json\game_franchises\game\84485.json
raw_json\game_franchises\game\84491.json
raw_json\game_franchises\game\84498.json
raw_json\game_franchises\game\84499.json
raw_json\game_franchises\game\845.json
raw_json\game_franchises\game\8450.json
raw_json\game_franchises\game\84500.json
raw_json\game_franchises\game\84501.json
raw_json\game_franchises\game\84502.json
raw_json\game_franchises\game\84504.json
raw_json\game_franchises\game\84509.json
raw_json\game_franchises\game\8451.json
raw_json\game_franchises\game\84513.json
raw_json\game_franchises\game\84515.json
raw_json\game_franchises\game\84516.json
raw_json\game_franchises\game\84517.json
raw_json\game_franchises\game\84518.json
raw_json\game_franchises\game\84519.json
raw_json\game_franchises\game\84526.json
raw_json\game_franchises\game\8453.json
raw_json\game_franchises\game\8454.json
raw_json\game_franchise

raw_json\game_franchises\game\85565.json
raw_json\game_franchises\game\85567.json
raw_json\game_franchises\game\85581.json
raw_json\game_franchises\game\85585.json
raw_json\game_franchises\game\85586.json
raw_json\game_franchises\game\85591.json
raw_json\game_franchises\game\85594.json
raw_json\game_franchises\game\85597.json
raw_json\game_franchises\game\85598.json
raw_json\game_franchises\game\8560.json
raw_json\game_franchises\game\85606.json
raw_json\game_franchises\game\85607.json
raw_json\game_franchises\game\85611.json
raw_json\game_franchises\game\85613.json
raw_json\game_franchises\game\85614.json
raw_json\game_franchises\game\85618.json
raw_json\game_franchises\game\8562.json
raw_json\game_franchises\game\8563.json
raw_json\game_franchises\game\85639.json
raw_json\game_franchises\game\85642.json
raw_json\game_franchises\game\85646.json
raw_json\game_franchises\game\85647.json
raw_json\game_franchises\game\85665.json
raw_json\game_franchises\game\85666.json
raw_json\game_franc

raw_json\game_franchises\game\86230.json
raw_json\game_franchises\game\86231.json
raw_json\game_franchises\game\86234.json
raw_json\game_franchises\game\86236.json
raw_json\game_franchises\game\86240.json
raw_json\game_franchises\game\86247.json
raw_json\game_franchises\game\86248.json
raw_json\game_franchises\game\86249.json
raw_json\game_franchises\game\86253.json
raw_json\game_franchises\game\86254.json
raw_json\game_franchises\game\86257.json
raw_json\game_franchises\game\86258.json
raw_json\game_franchises\game\86264.json
raw_json\game_franchises\game\86265.json
raw_json\game_franchises\game\86266.json
raw_json\game_franchises\game\86267.json
raw_json\game_franchises\game\8627.json
raw_json\game_franchises\game\86273.json
raw_json\game_franchises\game\86275.json
raw_json\game_franchises\game\86278.json
raw_json\game_franchises\game\8628.json
raw_json\game_franchises\game\8629.json
raw_json\game_franchises\game\86297.json
raw_json\game_franchises\game\863.json
raw_json\game_franchi

raw_json\game_franchises\game\86869.json
raw_json\game_franchises\game\8687.json
raw_json\game_franchises\game\86870.json
raw_json\game_franchises\game\86871.json
raw_json\game_franchises\game\86872.json
raw_json\game_franchises\game\86873.json
raw_json\game_franchises\game\86874.json
raw_json\game_franchises\game\86876.json
raw_json\game_franchises\game\86877.json
raw_json\game_franchises\game\86878.json
raw_json\game_franchises\game\8688.json
raw_json\game_franchises\game\86880.json
raw_json\game_franchises\game\86882.json
raw_json\game_franchises\game\86885.json
raw_json\game_franchises\game\86886.json
raw_json\game_franchises\game\86892.json
raw_json\game_franchises\game\86893.json
raw_json\game_franchises\game\86896.json
raw_json\game_franchises\game\86897.json
raw_json\game_franchises\game\86898.json
raw_json\game_franchises\game\86899.json
raw_json\game_franchises\game\86908.json
raw_json\game_franchises\game\86909.json
raw_json\game_franchises\game\8691.json
raw_json\game_franc

raw_json\game_franchises\game\87300.json
raw_json\game_franchises\game\87301.json
raw_json\game_franchises\game\87302.json
raw_json\game_franchises\game\87303.json
raw_json\game_franchises\game\87304.json
raw_json\game_franchises\game\87305.json
raw_json\game_franchises\game\87306.json
raw_json\game_franchises\game\87307.json
raw_json\game_franchises\game\87308.json
raw_json\game_franchises\game\87313.json
raw_json\game_franchises\game\87314.json
raw_json\game_franchises\game\87317.json
raw_json\game_franchises\game\8732.json
raw_json\game_franchises\game\87321.json
raw_json\game_franchises\game\87322.json
raw_json\game_franchises\game\87323.json
raw_json\game_franchises\game\87324.json
raw_json\game_franchises\game\87325.json
raw_json\game_franchises\game\87326.json
raw_json\game_franchises\game\87327.json
raw_json\game_franchises\game\87329.json
raw_json\game_franchises\game\8733.json
raw_json\game_franchises\game\87330.json
raw_json\game_franchises\game\87331.json
raw_json\game_fran

raw_json\game_franchises\game\88014.json
raw_json\game_franchises\game\88015.json
raw_json\game_franchises\game\88020.json
raw_json\game_franchises\game\88028.json
raw_json\game_franchises\game\8804.json
raw_json\game_franchises\game\88043.json
raw_json\game_franchises\game\88044.json
raw_json\game_franchises\game\88046.json
raw_json\game_franchises\game\8805.json
raw_json\game_franchises\game\88056.json
raw_json\game_franchises\game\88057.json
raw_json\game_franchises\game\88058.json
raw_json\game_franchises\game\88059.json
raw_json\game_franchises\game\8806.json
raw_json\game_franchises\game\88061.json
raw_json\game_franchises\game\88063.json
raw_json\game_franchises\game\88064.json
raw_json\game_franchises\game\88066.json
raw_json\game_franchises\game\88068.json
raw_json\game_franchises\game\88069.json
raw_json\game_franchises\game\8807.json
raw_json\game_franchises\game\88071.json
raw_json\game_franchises\game\88072.json
raw_json\game_franchises\game\88075.json
raw_json\game_franch

raw_json\game_franchises\game\8865.json
raw_json\game_franchises\game\88664.json
raw_json\game_franchises\game\88666.json
raw_json\game_franchises\game\8867.json
raw_json\game_franchises\game\88673.json
raw_json\game_franchises\game\88675.json
raw_json\game_franchises\game\88677.json
raw_json\game_franchises\game\88679.json
raw_json\game_franchises\game\88681.json
raw_json\game_franchises\game\88683.json
raw_json\game_franchises\game\88687.json
raw_json\game_franchises\game\88688.json
raw_json\game_franchises\game\8869.json
raw_json\game_franchises\game\88692.json
raw_json\game_franchises\game\88694.json
raw_json\game_franchises\game\88695.json
raw_json\game_franchises\game\8870.json
raw_json\game_franchises\game\88702.json
raw_json\game_franchises\game\88703.json
raw_json\game_franchises\game\88714.json
raw_json\game_franchises\game\88715.json
raw_json\game_franchises\game\88725.json
raw_json\game_franchises\game\88729.json
raw_json\game_franchises\game\8873.json
raw_json\game_franchi

raw_json\game_franchises\game\9256.json
raw_json\game_franchises\game\9258.json
raw_json\game_franchises\game\9259.json
raw_json\game_franchises\game\9264.json
raw_json\game_franchises\game\9265.json
raw_json\game_franchises\game\9267.json
raw_json\game_franchises\game\9269.json
raw_json\game_franchises\game\927.json
raw_json\game_franchises\game\9275.json
raw_json\game_franchises\game\9276.json
raw_json\game_franchises\game\9278.json
raw_json\game_franchises\game\928.json
raw_json\game_franchises\game\9281.json
raw_json\game_franchises\game\9282.json
raw_json\game_franchises\game\9283.json
raw_json\game_franchises\game\9286.json
raw_json\game_franchises\game\9287.json
raw_json\game_franchises\game\9288.json
raw_json\game_franchises\game\9289.json
raw_json\game_franchises\game\9292.json
raw_json\game_franchises\game\9295.json
raw_json\game_franchises\game\9299.json
raw_json\game_franchises\game\93.json
raw_json\game_franchises\game\9301.json
raw_json\game_franchises\game\9303.json
raw_

raw_json\game_franchises\game\9707.json
raw_json\game_franchises\game\9710.json
raw_json\game_franchises\game\9714.json
raw_json\game_franchises\game\9716.json
raw_json\game_franchises\game\9719.json
raw_json\game_franchises\game\9720.json
raw_json\game_franchises\game\9722.json
raw_json\game_franchises\game\9725.json
raw_json\game_franchises\game\9726.json
raw_json\game_franchises\game\9727.json
raw_json\game_franchises\game\9730.json
raw_json\game_franchises\game\9734.json
raw_json\game_franchises\game\9737.json
raw_json\game_franchises\game\9741.json
raw_json\game_franchises\game\9742.json
raw_json\game_franchises\game\9743.json
raw_json\game_franchises\game\9744.json
raw_json\game_franchises\game\9745.json
raw_json\game_franchises\game\9747.json
raw_json\game_franchises\game\9752.json
raw_json\game_franchises\game\9753.json
raw_json\game_franchises\game\9755.json
raw_json\game_franchises\game\9757.json
raw_json\game_franchises\game\9759.json
raw_json\game_franchises\game\9761.json


In [17]:
id_years_dict = list(zip(ids, release_years, aliases, developers, genres, platforms, publishers, rating))
id_year_df = pd.DataFrame.from_dict(id_years_dict)
id_year_df = id_year_df.rename(columns = {0:"id", 1:"release_year", 2:"aliases", 3: "developers", 4:"genres", 5: "platforms", 6: "publishers", 7: "rating"})
id_year_df = id_year_df.sort_values("id")
id_year_df

id  release_year                      2  \
0          1        1992.0  Desert Strike Advance   
9677       3           NaN                   None   
14192      4        1986.0                   None   
21240      6           NaN               SVR 2007   
26238      8           NaN         Battle Formula   
...      ...           ...                    ...   
28707  88822           NaN                   None   
28708  88824           NaN                   None   
28709  88831           NaN                   None   
28710  88834           NaN                   None   
28711  88837           NaN                   None   

                                                       3  \
0      [{'api_detail_url': 'https://www.giantbomb.com...   
9677   [{'api_detail_url': 'https://www.giantbomb.com...   
14192  [{'api_detail_url': 'https://www.giantbomb.com...   
21240  [{'api_detail_url': 'https://www.giantbomb.com...   
26238  [{'api_detail_url': 'https://www.giantbomb.com...   
...                                                  ...   
28707                                               None   
28708                                               None   
28709  [{'api_detail_url': 'https://www.giantbomb.com...   
28710  [{'api_detail_url': 'https://www.giantbomb.com...   
28711                                               None   

                                                       4  \
0      [{'api_detail_url': 'https://www.giantbomb.com...   
9677   [{'api_detail_url': 'https://www.giantbomb.com...   
14192  [{'api_detail_url': 'https://www.giantbomb.com...   
21240  [{'api_detail_url': 'https://www.giantbomb.com...   
26238  [{'api_detail_url': 'https://www.giantbomb.com...   
...                                                  ...   
28707  [{'api_detail_url': 'https://www.giantbomb.com...   
28708  [{'api_detail_url': 'https://www.giantbomb.com...   
28709  [{'api_detail_url': 'https://www.giantbomb.com...   
28710  [{'api_detail_url': 'https://www.giantbomb.com...   
28711  [{'api_detail_url': 'https://www.giantbomb.com...   

                                                       5  \
0      [{'api_detail_url': 'https://www.giantbomb.com...   
9677   [{'api_detail_url': 'https://www.giantbomb.com...   
14192  [{'api_detail_url': 'https://www.giantbomb.com...   
21240  [{'api_detail_url': 'https://www.giantbomb.com...   
26238  [{'api_detail_url': 'https://www.giantbomb.com...   
...                                                  ...   
28707  [{'api_detail_url': 'https://www.giantbomb.com...   
28708  [{'api_detail_url': 'https://www.giantbomb.com...   
28709  [{'api_detail_url': 'https://www.giantbomb.com...   
28710  [{'api_detail_url': 'https://www.giantbomb.com...   
28711  [{'api_detail_url': 'https://www.giantbomb.com...   

                                                       6  \
0      [{'api_detail_url': 'https://www.giantbomb.com...   
9677   [{'api_detail_url': 'https://www.giantbomb.com...   
14192  [{'api_detail_url': 'https://www.giantbomb.com...   
21240  [{'api_detail_url': 'https://www.giantbomb.com...   
26238  [{'api_detail_url': 'https://www.giantbomb.com...   
...                                                  ...   
28707  [{'api_detail_url': 'https://www.giantbomb.com...   
28708  [{'api_detail_url': 'https://www.giantbomb.com...   
28709  [{'api_detail_url': 'https://www.giantbomb.com...   
28710  [{'api_detail_url': 'https://www.giantbomb.com...   
28711  [{'api_detail_url': 'https://www.giantbomb.com...   

                                                       7  
0      [{'api_detail_url': 'https://www.giantbomb.com...  
9677                                                None  
14192                                               None  
21240  [{'api_detail_url': 'https://www.giantbomb.com...  
26238                                               None  
...                                                  ...  
28707  [{'api_detail_url': 'https://www.giantbomb.com...  
28708  [{'api_det

In [18]:
id_year_df = id_year_df.rename(columns = {2:"aliases", 3: "developers", 4:"genres", 5: "platforms", 6: "publishers", 7: "rating"})
id_year_df

id  release_year                aliases  \
0          1        1992.0  Desert Strike Advance   
9677       3           NaN                   None   
14192      4        1986.0                   None   
21240      6           NaN               SVR 2007   
26238      8           NaN         Battle Formula   
...      ...           ...                    ...   
28707  88822           NaN                   None   
28708  88824           NaN                   None   
28709  88831           NaN                   None   
28710  88834           NaN                   None   
28711  88837           NaN                   None   

                                              developers  \
0      [{'api_detail_url': 'https://www.giantbomb.com...   
9677   [{'api_detail_url': 'https://www.giantbomb.com...   
14192  [{'api_detail_url': 'https://www.giantbomb.com...   
21240  [{'api_detail_url': 'https://www.giantbomb.com...   
26238  [{'api_detail_url': 'https://www.giantbomb.com...   
...                                                  ...   
28707                                               None   
28708                                               None   
28709  [{'api_detail_url': 'https://www.giantbomb.com...   
28710  [{'api_detail_url': 'https://www.giantbomb.com...   
28711                                               None   

                                                  genres  \
0      [{'api_detail_url': 'https://www.giantbomb.com...   
9677   [{'api_detail_url': 'https://www.giantbomb.com...   
14192  [{'api_detail_url': 'https://www.giantbomb.com...   
21240  [{'api_detail_url': 'https://www.giantbomb.com...   
26238  [{'api_detail_url': 'https://www.giantbomb.com...   
...                                                  ...   
28707  [{'api_detail_url': 'https://www.giantbomb.com...   
28708  [{'api_detail_url': 'https://www.giantbomb.com...   
28709  [{'api_detail_url': 'https://www.giantbomb.com...   
28710  [{'api_detail_url': 'https://www.giantbomb.com...   
28711  [{'api_detail_url': 'https://www.giantbomb.com...   

                                               platforms  \
0      [{'api_detail_url': 'https://www.giantbomb.com...   
9677   [{'api_detail_url': 'https://www.giantbomb.com...   
14192  [{'api_detail_url': 'https://www.giantbomb.com...   
21240  [{'api_detail_url': 'https://www.giantbomb.com...   
26238  [{'api_detail_url': 'https://www.giantbomb.com...   
...                                                  ...   
28707  [{'api_detail_url': 'https://www.giantbomb.com...   
28708  [{'api_detail_url': 'https://www.giantbomb.com...   
28709  [{'api_detail_url': 'https://www.giantbomb.com...   
28710  [{'api_detail_url': 'https://www.giantbomb.com...   
28711  [{'api_detail_url': 'https://www.giantbomb.com...   

                                              publishers  \
0      [{'api_detail_url': 'https://www.giantbomb.com...   
9677   [{'api_detail_url': 'https://www.giantbomb.com...   
14192  [{'api_detail_url': 'https://www.giantbomb.com...   
21240  [{'api_detail_url': 'https://www.giantbomb.com...   
26238  [{'api_detail_url': 'https://www.giantbomb.com...   
...                                                  ...   
28707  [{'api_detail_url': 'https://www.giantbomb.com...   
28708  [{'api_detail_url': 'https://www.giantbomb.com...   
28709  [{'api_detail_url': 'https://www.giantbomb.com...   
28710  [{'api_detail_url': 'https://www.giantbomb.com...   
28711  [{'api_detail_url': 'https://www.giantbomb.com...   

                                                  rating  
0      [{'api_detail_url': 'https://www.giantbomb.com...  
9677                                                None  
14192                                               None  
21240  [{'api_detail_url': 'https://www.giantbomb.com...  
26238                                               None  
...                                                  ...  
28707  [{'api_detail_url': 'https://www.giantbomb.com...  
28708  [{'api_det

In [43]:
id_year_df["developers"] = id_year_df["developers"].apply(lambda x: [d["name"] for d in x] if x is not None else None)
id_year_df["genres"] = id_year_df["genres"].apply(lambda x: [d["name"] for d in x] if x is not None else None)
id_year_df["platforms"] = id_year_df["platforms"].apply(lambda x: [d["name"] for d in x] if x is not None else None)
id_year_df["publishers"] = id_year_df["publishers"].apply(lambda x: [d["name"] for d in x] if x is not None else None)
id_year_df["rating"] = id_year_df["rating"].apply(lambda x: [d["name"] for d in x] if x is not None else None)

In [52]:
id_year_df

id  release_year                aliases  \
0          1        1992.0  Desert Strike Advance   
9677       3           NaN                   None   
14192      4        1986.0                   None   
21240      6           NaN               SVR 2007   
26238      8           NaN         Battle Formula   
...      ...           ...                    ...   
28707  88822           NaN                   None   
28708  88824           NaN                   None   
28709  88831           NaN                   None   
28710  88834           NaN                   None   
28711  88837           NaN                   None   

                                              developers  \
0      [Electronic Arts, Visual Concepts, Budcat Crea...   
9677                                      [Kernel Kaput]   
14192  [The Software Toolworks, Software Country, Gam...   
21240       [Yuke's Co. Ltd., Digital Hearts Co., Ltd. ]   
26238                                [Tokai Engineering]   
...                                                  ...   
28707                                               None   
28708                                               None   
28709                                  [Magical Company]   
28710                                             [Sega]   
28711                                               None   

                              genres  \
0             [Action, Shoot 'Em Up]   
9677        [Action, Block-Breaking]   
14192  [Strategy, Trivia/Board Game]   
21240    [Action, Sports, Wrestling]   
26238             [Vehicular Combat]   
...                              ...   
28707               [Driving/Racing]   
28708                   [Simulation]   
28709            [Trivia/Board Game]   
28710                    [Adventure]   
28711            [Trivia/Board Game]   

                                               platforms  \
0      [Amiga, Game Boy, Game Boy Advance, Game Gear,...   
9677                                                [PC]   
14192  [Amiga, Amstrad CPC, Apple II, Atari ST, Commo...   
21240    [PlayStation Portable, PlayStation 2, Xbox 360]   
26238                    [Nintendo Entertainment System]   
...                                                  ...   
28707  [PC, PlayStation 4, Nintendo Switch, PlayStati...   
28708                                 [Game Boy Advance]   
28709                                      [PlayStation]   
28710                                          [Mac, PC]   
28711                                 [Game Boy Advance]   

                                              publishers  \
0      [Electronic Arts, Domark Software, Malibu Game...   
9677                        [Alawar Entertainment, Inc.]   
14192  [The Software Toolworks, Software Country, Ele...   
21240                                              [THQ]   
26238                                          [Sunsoft]   
...                                                  ...   
28707                                       [Koei Tecmo]   
28708                                         [TDK Core]   
28709                                  [Magical Company]   
28710                                             [Sega]   
28711                       [Hudson Entertainment, Inc.]   

                              rating  
0               [ESRB: K-A, ESRB: E]  
9677                            None  
14192                           None  
21240  [ESRB: T, PEGI: 16+, CERO: C]  
26238                           None  
...                              ...  
28707                      [CERO: A]  
28708               [CERO: All Ages]  
28709                           None  
28710                           None  
28711                           None  

[29208 rows x 8 columns]

In [54]:
id_year_df.to_csv("clean_game_metadata.csv")

Combine the dataframes and remove the redundant columns

In [90]:
games_ids = pd.merge(games_ids, id_year_df, how='left', left_on='game_id', right_on='id')
games_ids = games_ids.drop(["id","api_url"], axis = 1)
games_ids

franchise_id  game_id  \
0           3025-1      544   
1           3025-1     6649   
2           3025-1     7314   
3           3025-1     7358   
4           3025-1     7406   
...            ...      ...   
35112     3025-999    26577   
35113     3025-999    26575   
35114     3025-999    26581   
35115     3025-999    26580   
35116     3025-999    26606   

                                                    name  release_year  \
0              Super Mario All-Stars & Super Mario World        1994.0   
1                                   Super Mario Sunshine           NaN   
2                               Super Mario Bros. Deluxe           NaN   
3             Super Mario RPG: Legend of the Seven Stars           NaN   
4                                    Super Mario Bros. 2           NaN   
...                                                  ...           ...   
35112                       Shaman King: Funbari Spirits           NaN   
35113   Shaman King: Legacy of the Spirits, Soaring Hawk           NaN   
35114  Shaman King Chou Senjiryokketsu: Meramera/Funb...           NaN   
35115                           Shaman King: Soul Fight!           NaN   
35116                         Shaman King: Mirai no Ishi           NaN   

                                            aliases  \
0       Super Mario All-Stars and Super Mario World   
1                                              None   
2                              Super Mario Bros. DX   
3                                Mario RPG\r\nSMRPG   
4      Super Mario USA\nSuper Mario Bros. USA\nSMB2   
...                                             ...   
35112                                          None   
35113                                          None   
35114                                          None   
35115                                          None   
35116                                          None   

                         developers  \
0      [Nintendo EAD, SRD Co. Ltd.]   
1                    [Nintendo EAD]   
2                   [Nintendo R&D2]   
3         [Squaresoft, Square Enix]   
4      [Nintendo EAD, SRD Co. Ltd.]   
...                             ...   
35112           [Dimps Corporation]   
35113                          None   
35114            [Studio Saizensen]   
35115            [Bandai Co., Ltd.]   
35116  [Graphic Research Co., Ltd.]   

                                                  genres  \
0                              [Compilation, Platformer]   
1                         [Platformer, Action-Adventure]   
2      [Action, Adventure, Compilation, Puzzle, Platf...   
3                              [Adventure, Role-Playing]   
4                                           [Platformer]   
...                                                  ...   
35112                                         [Fighting]   
35113                                     [Role-Playing]   
35114                                           [Action]   
35115                                         [Fighting]   
35116                                               None   

                                               platforms          publishers  \
0                  [Super Nintendo Entertainment System]          [Nintendo]   
1                            [GameCube, Nintendo Switch]          [Nintendo]   
2                   [Game Boy Color, Nintendo 3DS eShop]          [Nintendo]   
3      [Super Nintendo Entertainment System, Wii Shop...          [Nintendo]   
4      [Nintendo Entertainment System, Wii Shop, Nint...          [Nintendo]   
...                                                  ...                 ...   
35112                                    [PlayStation 2]  [Bandai Co., Ltd.]   
35113                                 [Game Boy Advance]            [Konami]   
35114                                   [Game Boy Color]      [King Records]   
35115                                         [GameCube]  [Bandai Co., Ltd.]   
35116        

Finally we'll export all the collected data to a csv file. 

In [91]:
games_ids.to_csv("clean_giantbomb_games_db.csv")